/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR DISCHARGE TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  LAXMAN MANANDHAR
REVIEWED BY: DIPAK THAPA,SURUCHI,
DATE : 20TH NOVEMBER, 2018
*/



UPDATE CONCEPT_NAME SET NAME= 'Disccharge note'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Admission date'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Admission Date';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Discharge date'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Discharge Date';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Discharged to'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Discharged to';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Diagnosis'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Diagnosis';
UPDATE CONCEPT_NAME SET NAME= 'Recovered'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Recovered';
UPDATE CONCEPT_NAME SET NAME= 'Not improved'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not Improved';
UPDATE CONCEPT_NAME SET NAME= 'Referred out'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred out';
UPDATE CONCEPT_NAME SET NAME= 'Referred on request'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred on request';
UPDATE CONCEPT_NAME SET NAME= 'LAMA/DAMA'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='LAMA/DAMA';
UPDATE CONCEPT_NAME SET NAME= 'DOR'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='DOR';
UPDATE CONCEPT_NAME SET NAME= 'Absconded'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Absconded';
UPDATE CONCEPT_NAME SET NAME= 'Death<48 Hours'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Death < 48 Hours';
UPDATE CONCEPT_NAME SET NAME= 'Death>48 Hours'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Death>48 Hours';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Inpatient outcome'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge note, Inpatient outcome';
UPDATE CONCEPT_NAME SET NAME= 'Open reduction internal fixation'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Open Reduction Internal Fixation';
UPDATE CONCEPT_NAME SET NAME= 'Intra-abdominal/thoracic'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Intra-abdominal/thoracic';
UPDATE CONCEPT_NAME SET NAME= 'Other'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Other';
UPDATE CONCEPT_NAME SET NAME= 'None'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='None';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Major surgery in this admission'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-Major surgery this admission';
UPDATE CONCEPT_NAME SET NAME= 'Antibiotics given-prophylaxis'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Antibiotics given for prophylaxis';
UPDATE CONCEPT_NAME SET NAME= 'Blood products given '  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Blood products given based on protocol or patient\'s arrival state';
UPDATE CONCEPT_NAME SET NAME= 'Antibiotics given-post operative'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Antibiotics given to treat post-operative complication';
UPDATE CONCEPT_NAME SET NAME= 'Blood products given-post operative'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Blood products given to treat post-operative complication';
UPDATE CONCEPT_NAME SET NAME= 'Failed/aborted surgery'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Failed or aborted surgery';
UPDATE CONCEPT_NAME SET NAME= 'Death'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Death';
UPDATE CONCEPT_NAME SET NAME= 'None'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='None';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Post operative complications '  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-Post op surgery complications';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Brief hospital course'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Brief Hospital Course';
UPDATE CONCEPT_NAME SET NAME= 'Condoms'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Condoms';
UPDATE CONCEPT_NAME SET NAME= 'Tubectomy'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Tubectomy';
UPDATE CONCEPT_NAME SET NAME= 'Pills'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pills';
UPDATE CONCEPT_NAME SET NAME= 'LAM'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Lactational Amenorrhea Method';
UPDATE CONCEPT_NAME SET NAME= 'Depo'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Depo';
UPDATE CONCEPT_NAME SET NAME= 'Implant'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Implant';
UPDATE CONCEPT_NAME SET NAME= 'IUCD'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Intra Uterine Contraceptive Device';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Contraceptive chosen'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-Contraceptive Chosen';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Transportation incentive'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-Transportation Incentive';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-ANC incentive'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-ANC Incentive';
UPDATE CONCEPT_NAME SET NAME= 'Normal'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Normal';
UPDATE CONCEPT_NAME SET NAME= 'Asphyxiated'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Asphyxiated';
UPDATE CONCEPT_NAME SET NAME= 'Still birth'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC program outcomes, Still Birth';
UPDATE CONCEPT_NAME SET NAME= 'Defects'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Defects';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Infant condition'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-Infant Condition';
UPDATE CONCEPT_NAME SET NAME= 'Asphyxiated'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Asphyxiated';
UPDATE CONCEPT_NAME SET NAME= 'Hypothermia'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Hypothermia';
UPDATE CONCEPT_NAME SET NAME= 'Hypoglycemia'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Complications, Hypoglycemia';
UPDATE CONCEPT_NAME SET NAME= 'Neonatal sepsis'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Neonatal Sepsis';
UPDATE CONCEPT_NAME SET NAME= 'Infection'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Burn Note-Infection';
UPDATE CONCEPT_NAME SET NAME= 'Jaundice'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Jaundice';
UPDATE CONCEPT_NAME SET NAME= 'Difficulty feeding'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Difficulty Feeding';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Complications during hospital stay'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge note, Complications during hospital stay';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Intervention during hospital stay'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge note, Intervention during hospital stay';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-IMAM admission weight'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-IMAM admission Weight';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-IMAM discharge weight'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-IMAM discharge weight';
UPDATE CONCEPT_NAME SET NAME= 'Recovered'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Recovered';
UPDATE CONCEPT_NAME SET NAME= 'Not improved'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not Improved';
UPDATE CONCEPT_NAME SET NAME= 'Defaulter'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Defaulter ? DF';
UPDATE CONCEPT_NAME SET NAME= 'Absconded'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Absconded';
UPDATE CONCEPT_NAME SET NAME= 'Death'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Death';
UPDATE CONCEPT_NAME SET NAME= 'IMAM-Discharge status'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='IMAM-Discharge Status';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Medication on dhscharge'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Medications on Discharged';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Followup instructions'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Followup Instructions';
UPDATE CONCEPT_NAME SET NAME= 'Discharge note-Name of the doctor for more information'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Name of Doctor to contact for more information';

UPDATE CONCEPT_NAME SET NAME= 'Disccharge note'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Disccharge note' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Date of admission'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Admission date' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Date of discharge'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Discharge date' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Discharged to'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Discharged to' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Diagnosis'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Diagnosis' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Recovered'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Recovered' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Not improved'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Not improved' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Referred out'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Referred out' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Referred on request'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Referred on request' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'LAMA/DAMA'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'LAMA/DAMA' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'DOR'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'DOR' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Absconded'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Absconded' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Death < 48 Hours'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Death<48 Hours' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Death>48 Hours'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Death>48 Hours' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Inpatient outcome'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Inpatient outcome' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'ORIF'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Open reduction internal fixation' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Intra-abdominal/thoracic'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Intra-abdominal/thoracic' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Other'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Other' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'None'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'None' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Major surgery performed this admission?'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Major surgery in this admission' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Antibiotics given for prophylaxis'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Antibiotics given-prophylaxis' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Blood products given based on protocol or patient\'s arrival state'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Blood products given ' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Antibiotics given to treat post-operative complication'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Antibiotics given-post operative' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Blood products given to treat post-operative complication'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Blood products given-post operative' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Failed or aborted surgery'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Failed/aborted surgery' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Death'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Death' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'None'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'None' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Did any of the following occur during the post-operative period?'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Post operative complications ' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Brief hospital course'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Brief hospital course' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Condoms'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Condoms' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Tubectomy'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Tubectomy' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Pills'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Pills' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'LAM'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'LAM' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Depo'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Depo' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Implant'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Implant' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'IUCD'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'IUCD' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Contraceptive chosen'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Contraceptive chosen' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Transportation incentive'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Transportation incentive' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'ANC incentive'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-ANC incentive' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Normal'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Normal' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Asphyxiated'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Asphyxiated' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Still birth'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Still birth' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Defects'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Defects' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Infant condition'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Infant condition' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Asphyxiated'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Asphyxiated' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Hypothermia'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Hypothermia' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Hypoglycemia'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Hypoglycemia' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Neonatal sepsis'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Neonatal sepsis' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Infection'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Infection' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Jaundice'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Jaundice' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Difficulty feeding'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Difficulty feeding' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Complications during hospital stay'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Complications during hospital stay' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Intervention during hospital stay'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Intervention during hospital stay' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'IMAM admission weight'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-IMAM admission weight' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'IMAM discharge weight'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-IMAM discharge weight' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Recovered'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Recovered' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Not improved'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Not improved' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Defaulter'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Defaulter' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Absconded'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Absconded' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Death'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Death' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Discharge status'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'IMAM-Discharge status' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Medication on dhscharge'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Medication on dhscharge' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Followup instructions'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Followup instructions' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= 'Name of the doctor for more information'  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = 'Discharge note-Name of the doctor for more information' AND concept_name_type='FULLY_SPECIFIED');
UPDATE CONCEPT_NAME SET NAME= ''  WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT CONCEPT_ID FROM CONCEPT_NAME WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED');