/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR IMAM PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/


UPDATE concept_name SET NAME= '2nd month' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='2nd month';
UPDATE concept_name SET NAME= '3rd month' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='3rd month';
UPDATE concept_name SET NAME= '4th month' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='4th month';
UPDATE concept_name SET NAME= '5th month' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='5th month';
UPDATE concept_name SET NAME= '6th month' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='6th month';
UPDATE concept_name SET NAME= '7th month' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='7th month';
UPDATE concept_name SET NAME= '8th month' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='8th month';
UPDATE concept_name SET NAME= '9th month' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='9th month';
UPDATE concept_name SET NAME= 'ANC-Visit month' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Visit Month';
UPDATE concept_name SET NAME= 'ANC-1st (any time)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, 1st (any time)';
UPDATE concept_name SET NAME= 'ANC-1st (per protocol)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, 1st (per protocol)';
UPDATE concept_name SET NAME= 'ANC-2nd (per protocol)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, 2nd (per protocol)';
UPDATE concept_name SET NAME= 'ANC-3rd (per protocol)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, 3rd (per protocol)';
UPDATE concept_name SET NAME= 'ANC-4th (per protocol)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, 4th (per protocol)';
UPDATE concept_name SET NAME= 'ANC-ANC visit' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, ANC Visit, Other';
UPDATE concept_name SET NAME= 'ANC-ANC visit' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, ANC Visit';
UPDATE concept_name SET NAME= 'ANC-Completed 4 anc visits' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Completed 4 ANC visits';
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred In';
UPDATE concept_name SET NAME= 'ANC-History of abortion' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-History of Abortion';
UPDATE concept_name SET NAME= 'ANC-Present live children' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Present Live Children';
UPDATE concept_name SET NAME= 'ANC-Gravida' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Gravida';
UPDATE concept_name SET NAME= 'ANC-Parity' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Parity';
UPDATE concept_name SET NAME= 'ANC-Last menstrual period' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Last Menstrual Period';
UPDATE concept_name SET NAME= 'ANC-Expected delivery date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Expected Delivery Date';
UPDATE concept_name SET NAME= 'ANC-First td' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, First TD';
UPDATE concept_name SET NAME= 'ANC-Second td' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Second TD';
UPDATE concept_name SET NAME= 'ANC-2plus td' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, 2plus TD';
UPDATE concept_name SET NAME= 'ANC-TD given' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, TD Given';
UPDATE concept_name SET NAME= 'Yes' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Yes';
UPDATE concept_name SET NAME= 'No' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='No';
UPDATE concept_name SET NAME= 'ANC-Already taken' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Already Taken';
UPDATE concept_name SET NAME= 'ANC-Albendazole given' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Albendazole given';
UPDATE concept_name SET NAME= 'ANC-Number of iron tablets given' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Number of Iron Tablets given';
UPDATE concept_name SET NAME= 'ANC-Folic acid provided' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Folic acid Provided';
UPDATE concept_name SET NAME= 'ANC-Blood transfusion provided' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Blood Transfusion Provided';
UPDATE concept_name SET NAME= 'ANC-Blood transfusion quantity' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Blood Transfusion Quantity';
UPDATE concept_name SET NAME= 'TRUE' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TRUE';
UPDATE concept_name SET NAME= 'FALSE' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FALSE';
UPDATE concept_name SET NAME= 'Not applicable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not Applicable';
UPDATE concept_name SET NAME= 'ANC-Gestational diabetes screening' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Gestational Diabetes Screening';
UPDATE concept_name SET NAME= 'Previous C-section' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Previous C-section';
UPDATE concept_name SET NAME= 'RH negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='RH Negative';
UPDATE concept_name SET NAME= 'Hepatitis b' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Hepatitis B';
UPDATE concept_name SET NAME= 'Hepatitis c' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Hepatitis C';
UPDATE concept_name SET NAME= 'Side effect-Anemia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Side effect, Anemia';
UPDATE concept_name SET NAME= 'New onset hypertension in pregnancy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='New onset hypertension in pregnancy';
UPDATE concept_name SET NAME= 'Chronic hypertension in pregnancy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Chronic hypertension in pregnancy';
UPDATE concept_name SET NAME= 'Pre-existing diabetes' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pre-existing diabetes';
UPDATE concept_name SET NAME= 'HIV positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIV positive';
UPDATE concept_name SET NAME= 'Syphilis positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Syphilis Positive';
UPDATE concept_name SET NAME= 'ANC-Gestational diabetes' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Gestational Diabetes';
UPDATE concept_name SET NAME= 'Hydrocephalus' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Hydrocephalus';
UPDATE concept_name SET NAME= 'ANC-USG polyhydramnios' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-USG Polyhydramnios';
UPDATE concept_name SET NAME= 'Analcephaly' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Analcephaly';
UPDATE concept_name SET NAME= 'ANC-High risk pregnancy diagnosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-High Risk Pregnancy Diagnosis';
UPDATE concept_name SET NAME= 'Ectopic pregnancy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Ectopic Pregnancy';
UPDATE concept_name SET NAME= 'Antepartum haemorrhage' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Antepartum Haemorrhage';
UPDATE concept_name SET NAME= 'Abortion complication' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Abortion Complication';
UPDATE concept_name SET NAME= 'Pregnancy induced hypertension' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pregnancy Induced Hypertension';
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not present';
UPDATE concept_name SET NAME= 'ANC-Obstetric complication' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Obstetric Complication';
UPDATE concept_name SET NAME= 'Other obstructive complications' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Other Obstructive Complications';
UPDATE concept_name SET NAME= 'ANC-Condoms given' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Condoms given';
UPDATE concept_name SET NAME= 'ANC-HIV counseling' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, HIV Counseling';
UPDATE concept_name SET NAME= 'ANC-HIV testing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, HIV Testing';
UPDATE concept_name SET NAME= 'ANC-HIV test date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, HIV Test Date';
UPDATE concept_name SET NAME= 'ANC-HIV result received' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, HIV Result Received';
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Positive';
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Negative';
UPDATE concept_name SET NAME= 'ANC-HIV test result' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, HIV Test Result';
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Positive';
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Negative';
UPDATE concept_name SET NAME= 'Unknown' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Unknown';
UPDATE concept_name SET NAME= 'ANC-Partner hiv status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Partner HIV Status';
UPDATE concept_name SET NAME= 'ANC-Partner referred' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Partner Referred';
UPDATE concept_name SET NAME= 'ANC-ART started' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, ART Started';
UPDATE concept_name SET NAME= 'ANC-ART start date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, ART Start Date';
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Positive';
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Negative';
UPDATE concept_name SET NAME= 'ANC-Second result' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Second Result';
UPDATE concept_name SET NAME= 'ANC-CHX' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-CHX';
UPDATE concept_name SET NAME= 'ANC-Own' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Own';
UPDATE concept_name SET NAME= 'ANC-Kin' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Kin';
UPDATE concept_name SET NAME= 'ANC-Mother's contact number' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Mother's contact number';
UPDATE concept_name SET NAME= 'ANC-Number' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Number';
UPDATE concept_name SET NAME= 'ANC-Guardian name' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Guardian name';
UPDATE concept_name SET NAME= 'Relationship-Husband' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Relationship-Husband';
UPDATE concept_name SET NAME= 'Relationship-Family member' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Relationship-Family member';
UPDATE concept_name SET NAME= 'Relationship-Next to kin' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Relationship-Next to Kin';
UPDATE concept_name SET NAME= 'Relationship-Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Relationship-Others';
UPDATE concept_name SET NAME= 'ANC-Guardian relationship' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Guardian Relationship';
UPDATE concept_name SET NAME= 'ANC-Diagnosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Diagnois';
UPDATE concept_name SET NAME= 'ANC-HIV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, HIV';
UPDATE concept_name SET NAME= 'ANC-Syphilis counseling' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Syphilis Counseling';
UPDATE concept_name SET NAME= 'ANC-Syphilis tested' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Syphilis Tested';
UPDATE concept_name SET NAME= 'ANC-Syphilis tereated' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC, Syphilis Treated';
UPDATE concept_name SET NAME= 'Syphili NOS' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Syphilis NOS';
UPDATE concept_name SET NAME= 'Antenatal checkup(ANC) note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC';




UPDATE concept_name SET NAME= 'New' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'New' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Re-visit' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Re-visit' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Visit type' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-visit type' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Referred in' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Number of living children' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Number of living children' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'FCHV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FCHV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Healthcare provider' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Healthcare provider' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Referred by' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-Referred by' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Weeks of current gestation by LMP method' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Weeks of current gestation by LMP method' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Weeks of current gestation by examination' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Weeks of current gestation by examination' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pain management given' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pain management given' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'MVA' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Manual vacuum aspiration' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Dilation and evacuation' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Dilation and evacuation' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Electric vacuum aspiration' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Electric vacuum aspiration' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Other abortion procedures' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'NA' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not applicable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Surgical procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-surgical procedure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others(specify)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-others(specify)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Bleeding requiring >1 pint of iv fluid' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Bleeding requiring >1 pint of iv fluid' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Bleeding requiring blood transfusion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Bleeding requiring blood transfusion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'abdominal injury' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Uterine or intra-abdominal injury' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Immediate complications' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Surgical Abortion-Immediate complications' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Medical abortion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-Medical abortion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Medical induction' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Medical induction' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Other abortion procedures' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'NA' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not applicable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Medical procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-medical procedure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others(specify)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-others(specify)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Surgical abortion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-Surgical abortion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Medical abortion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Medical abortion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Spontaneous abortion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PAC Cause-Spontaneous abortion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'NA' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not applicable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cause' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PAC cause' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'BH' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-bayalpata hospital' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other hf' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Other health facilities' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Abortion done at' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-abortion done at' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Bleeding requiring >1 pint of iv fluid' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Bleeding requiring >1 pint of iv fluid' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Bleeding requiring blood transfusion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Bleeding requiring blood transfusion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Infection requiring hospitalization/iv antibiotics' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Infection requiring hospitalization/iv antibiotics' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Medical complication' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA:pac-medical complication' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Incomplete abortion requiring repeat procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Incomplete abortion requiring repeat procedure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Requiring laparotomy' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Requiring laparotomy' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Infection requiring hospitalization/iv antibiotics' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Infection requiring hospitalization/iv antibiotics' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Failed abortion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Failed abortion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Septic abortion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Septic abortion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'abdominal injury' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Uterine or intra-abdominal injury' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Surgical complication' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA:pac-surgical complication' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'MVA' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Manual vacuum aspiration' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Other' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'PAC procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-PAC procedure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Condoms' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pills' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Depo provera' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Depo provera' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Female sterilization' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Female sterilization' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Male sterilization' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Male sterilization' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Implant' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'IUCD' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Accepted family planning methods' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Accepted family planning methods' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Name' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-Service provider name' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Listed number' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-listed number' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Normal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Normal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Leaving against medical advice' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Leaving against medical advice' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Referred out' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Referred out' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Death' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Death' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Outcome of cac/pac' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Outcome of cac/pac' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Follow up in' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Childhood illness - counseling - follow up' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Remarks' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-Remarks' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Surgical abortion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-Surgical abortion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Medical abortion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-Medical abortion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'PAC diagnosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-PAC diagnosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Post abortioon care' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-Post abortioon care' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Details of service provider' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SA-Details of service provider' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Safe abortion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Safe abortion (SA) note' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
