/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR DISCHARGE PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/

UPDATE concept_name SET NAME= 'Discharge note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note';
UPDATE concept_name SET NAME= 'Discharge note-Admission date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Admission Date';
UPDATE concept_name SET NAME= 'Discharge note-Discharge date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Discharge Date';
UPDATE concept_name SET NAME= 'Discharge note-Discharged to' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Discharged to';
UPDATE concept_name SET NAME= 'Discharge note-Diagnosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Diagnosis';
UPDATE concept_name SET NAME= 'Recovered' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Recovered';
UPDATE concept_name SET NAME= 'Not improved' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not Improved';
UPDATE concept_name SET NAME= 'Referred out' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred out';
UPDATE concept_name SET NAME= 'Referred on request' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred on request';
UPDATE concept_name SET NAME= 'LAMA/DAMA' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='LAMA/DAMA';
UPDATE concept_name SET NAME= 'DOR' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='DOR';
UPDATE concept_name SET NAME= 'Absconded' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Absconded';
UPDATE concept_name SET NAME= 'Death<48 Hours' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Death < 48 Hours';
UPDATE concept_name SET NAME= 'Death>48 Hours' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Death>48 Hours';
UPDATE concept_name SET NAME= 'Discharge note-Inpatient outcome' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge note, Inpatient outcome';
UPDATE concept_name SET NAME= 'Open reduction internal fixation' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Open Reduction Internal Fixation';
UPDATE concept_name SET NAME= 'Intra-abdominal/thoracic' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Intra-abdominal/thoracic';
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Other';
UPDATE concept_name SET NAME= 'None' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='None';
UPDATE concept_name SET NAME= 'Discharge note-Major surgery in this admission' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-Major surgery this admission';
UPDATE concept_name SET NAME= 'Antibiotics given-prophylaxis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Antibiotics given for prophylaxis';
UPDATE concept_name SET NAME= 'Blood products given ' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Blood products given based on protocol or patient's arrival state';
UPDATE concept_name SET NAME= 'Antibiotics given-post operative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Antibiotics given to treat post-operative complication';
UPDATE concept_name SET NAME= 'Blood products given-post operative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Blood products given to treat post-operative complication';
UPDATE concept_name SET NAME= 'Failed/aborted surgery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Failed or aborted surgery';
UPDATE concept_name SET NAME= 'Death' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Death';
UPDATE concept_name SET NAME= 'None' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='None';
UPDATE concept_name SET NAME= 'Discharge note-Post operative complications ' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-Post op surgery complications';
UPDATE concept_name SET NAME= 'Discharge note-Brief hospital course' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Brief Hospital Course';
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Condoms';
UPDATE concept_name SET NAME= 'Tubectomy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Tubectomy';
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pills';
UPDATE concept_name SET NAME= 'LAM' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Lactational Amenorrhea Method';
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Depo';
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Implant';
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Intra Uterine Contraceptive Device';
UPDATE concept_name SET NAME= 'Discharge note-Contraceptive chosen' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-Contraceptive Chosen';
UPDATE concept_name SET NAME= 'Discharge note-Transportation incentive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-Transportation Incentive';
UPDATE concept_name SET NAME= 'Discharge note-ANC incentive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-ANC Incentive';
UPDATE concept_name SET NAME= 'Normal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Normal';
UPDATE concept_name SET NAME= 'Asphyxiated' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Asphyxiated';
UPDATE concept_name SET NAME= 'Still birth' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC program outcomes, Still Birth';
UPDATE concept_name SET NAME= 'Defects' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Defects';
UPDATE concept_name SET NAME= 'Discharge note-Infant condition' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-Infant Condition';
UPDATE concept_name SET NAME= 'Asphyxiated' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Asphyxiated';
UPDATE concept_name SET NAME= 'Hypothermia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Hypothermia';
UPDATE concept_name SET NAME= 'Hypoglycemia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Complications, Hypoglycemia';
UPDATE concept_name SET NAME= 'Neonatal sepsis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Neonatal Sepsis';
UPDATE concept_name SET NAME= 'Infection' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Burn Note-Infection';
UPDATE concept_name SET NAME= 'Jaundice' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Jaundice';
UPDATE concept_name SET NAME= 'Difficulty feeding' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Difficulty Feeding';
UPDATE concept_name SET NAME= 'Discharge note-Complications during hospital stay' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge note, Complications during hospital stay';
UPDATE concept_name SET NAME= 'Discharge note-Intervention during hospital stay' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge note, Intervention during hospital stay';
UPDATE concept_name SET NAME= 'Discharge note-IMAM admission weight' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-IMAM admission Weight';
UPDATE concept_name SET NAME= 'Discharge note-IMAM discharge weight' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note-IMAM discharge weight';
UPDATE concept_name SET NAME= 'Recovered' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Recovered';
UPDATE concept_name SET NAME= 'Not improved' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not Improved';
UPDATE concept_name SET NAME= 'Defaulter' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Defaulter ? DF';
UPDATE concept_name SET NAME= 'Absconded' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Absconded';
UPDATE concept_name SET NAME= 'Death' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Death';
UPDATE concept_name SET NAME= 'IMAM-Discharge status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='IMAM-Discharge Status';
UPDATE concept_name SET NAME= 'Discharge note-Medication on discharge' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Medications on Discharged';
UPDATE concept_name SET NAME= 'Discharge note-Followup instructions' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Followup Instructions';
UPDATE concept_name SET NAME= 'Discharge note-Name of the doctor for more information' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Discharge Note, Name of Doctor to contact for more information';


UPDATE concept_name SET NAME= 'Discharge note' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Date of admission' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Admission date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Date of discharge' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Discharge date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Discharged to' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Discharged to' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diagnosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Diagnosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Recovered' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Recovered' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Not improved' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not improved' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Referred out' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Referred out' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Referred on request' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Referred on request' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'LAMA/DAMA' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'LAMA/DAMA' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'DOR' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'DOR' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Absconded' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Absconded' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Death < 48 Hours' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Death<48 Hours' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Death>48 Hours' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Death>48 Hours' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Inpatient outcome' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Inpatient outcome' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ORIF' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Open reduction internal fixation' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Intra-abdominal/thoracic' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Intra-abdominal/thoracic' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Other' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'None' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'None' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Major surgery performed this admission?' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Major surgery in this admission' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Antibiotics given for prophylaxis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Antibiotics given-prophylaxis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Blood products given based on protocol or patient's arrival state' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Blood products given ' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Antibiotics given to treat post-operative complication' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Antibiotics given-post operative' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Blood products given to treat post-operative complication' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Blood products given-post operative' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Failed or aborted surgery' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Failed/aborted surgery' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Death' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Death' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'None' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'None' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Did any of the following occur during the post-operative period?' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Post operative complications ' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Brief hospital course' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Brief hospital course' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Condoms' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Tubectomy' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Tubectomy' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pills' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'LAM' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'LAM' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Depo' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Implant' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'IUCD' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Contraceptive chosen' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Contraceptive chosen' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Transportation incentive' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Transportation incentive' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ANC incentive' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-ANC incentive' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Normal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Normal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Asphyxiated' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Asphyxiated' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Still birth' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Still birth' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Defects' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Defects' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Infant condition' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Infant condition' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Asphyxiated' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Asphyxiated' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Hypothermia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Hypothermia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Hypoglycemia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Hypoglycemia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Neonatal sepsis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Neonatal sepsis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Infection' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Infection' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Jaundice' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Jaundice' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Difficulty feeding' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Difficulty feeding' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Complications during hospital stay' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Complications during hospital stay' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Intervention during hospital stay' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Intervention during hospital stay' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IMAM admission weight' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-IMAM admission weight' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IMAM discharge weight' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-IMAM discharge weight' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Recovered' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Recovered' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Not improved' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not improved' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Defaulter' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Defaulter' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Absconded' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Absconded' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Death' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Death' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Discharge status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'IMAM-Discharge status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Medication on discharge' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Medication on discharge' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Followup instructions' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Followup instructions' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Name of the doctor for more information' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Discharge note-Name of the doctor for more information' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );