/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR PROCEDURE NOTE PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/


INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),curdate(),changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Physiotherapy, Shoulder, ROM' LIMIT 1  ;

INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),curdate(),changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Physiotherapy exercises' LIMIT 1  ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),curdate(),changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Procedure Notes' LIMIT 1  ;


UPDATE concept_name SET NAME= 'Procedure note-Diagnosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Diagnosis';
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred In';
UPDATE concept_name SET NAME= 'Procedure Note-HIV counselling' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Note, HIV Counselling';
UPDATE concept_name SET NAME= 'Procedure Note-Consent' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Note-Consent';
UPDATE concept_name SET NAME= 'Procedure note-Anesthetist' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Anesthetist';
UPDATE concept_name SET NAME= 'Procedure note-Preoperative meds' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Preoperative Meds';
UPDATE concept_name SET NAME= 'Procedure note-Surgeons' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Surgeons';
UPDATE concept_name SET NAME= 'Scrub nurse' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Scrub Nurse';
UPDATE concept_name SET NAME= 'Circulating nurse' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Circulating Nurse';
UPDATE concept_name SET NAME= 'Procedures-Other staff' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedures, Other Staff';
UPDATE concept_name SET NAME= 'Cathetrigetion' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cathetrigetion';
UPDATE concept_name SET NAME= 'Dilatation' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Dilatation';
UPDATE concept_name SET NAME= 'Excision' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Excision';
UPDATE concept_name SET NAME= 'Figure 8 bandage' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Figure 8 Bandage';
UPDATE concept_name SET NAME= 'Foreign body removal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Foreign Body Removal';
UPDATE concept_name SET NAME= 'First time dressing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='First Time Dressing';
UPDATE concept_name SET NAME= 'Follow-up dressing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Follow-up Dressing';
UPDATE concept_name SET NAME= 'Incision and drainage' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Incision and Drainage';
UPDATE concept_name SET NAME= 'Norplant removal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Norplant Removal';
UPDATE concept_name SET NAME= 'Retrzetion' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Retrzetion';
UPDATE concept_name SET NAME= 'Suture in' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Suture In';
UPDATE concept_name SET NAME= 'Suture out' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Suture Out';
UPDATE concept_name SET NAME= 'Syringing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Syringing';
UPDATE concept_name SET NAME= 'Orthopedic procedure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Orthopedic procedure';
UPDATE concept_name SET NAME= 'Other procedure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Other procedure';
UPDATE concept_name SET NAME= 'Procedure note-Procedure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Procedure';
UPDATE concept_name SET NAME= 'Procedure note-Specific intervention' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Specific Intervention';
UPDATE concept_name SET NAME= 'Above elbow' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Above Elbow';
UPDATE concept_name SET NAME= 'Below elbow' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Below Elbow';
UPDATE concept_name SET NAME= 'Above knee' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Above Knee';
UPDATE concept_name SET NAME= 'Below knee' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Below Knee';
UPDATE concept_name SET NAME= 'Procedure note-Ortho procedure location' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Ortho Procedure Location';
UPDATE concept_name SET NAME= 'Cast application' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cast application';
UPDATE concept_name SET NAME= 'Cast adjustment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cast adjustment';
UPDATE concept_name SET NAME= 'Cast removal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cast removal';
UPDATE concept_name SET NAME= 'Slab application' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Slab application';
UPDATE concept_name SET NAME= 'Slab removal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Slab removal';
UPDATE concept_name SET NAME= 'Scaphoid cast' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Scaphoid cast';
UPDATE concept_name SET NAME= 'Thumb spica cast' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Thumb Spica Cast';
UPDATE concept_name SET NAME= 'Olecranon brace (ocb)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Olecranon Brace (OCB)';
UPDATE concept_name SET NAME= 'Patellar tendon brace (PTB)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Patellar Tendon Brace (PTB)';
UPDATE concept_name SET NAME= 'Wound inspection' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Wound Inspection';
UPDATE concept_name SET NAME= 'First time dressing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='First Time Dressing';
UPDATE concept_name SET NAME= 'Follow-up dressing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Follow-up Dressing';
UPDATE concept_name SET NAME= 'K-wire removal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='K-wire removal';
UPDATE concept_name SET NAME= 'Triangular sling application' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Triangular Sling application';
UPDATE concept_name SET NAME= 'Cuff and collar sling application' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cuff and Collar Sling application';
UPDATE concept_name SET NAME= 'High groin cast' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='High Groin Cast';
UPDATE concept_name SET NAME= 'Crepe bandage application' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Crepe bandage application';
UPDATE concept_name SET NAME= 'Cyst removal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cyst Removal';
UPDATE concept_name SET NAME= 'Figure 8 bandage' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Figure 8 Bandage';
UPDATE concept_name SET NAME= 'Foreign body removal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Foreign Body Removal';
UPDATE concept_name SET NAME= 'Hip spica' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Hip Spica';
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Other';
UPDATE concept_name SET NAME= 'Procedure note-Ortho procedure and other' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Ortho Procedure, Procedure';
UPDATE concept_name SET NAME= 'Procedure note-Local anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Type of anesthesia, Local';
UPDATE concept_name SET NAME= 'Procedure note-Regional anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Type of anesthesia, Regional';
UPDATE concept_name SET NAME= 'Procedure note-General anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Type of anesthesia, General';
UPDATE concept_name SET NAME= 'None' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Type of anesthesia, None';
UPDATE concept_name SET NAME= 'Procedure note-Type of anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Type of anesthesia';
UPDATE concept_name SET NAME= 'Procedure note-Anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Anesthesia';
UPDATE concept_name SET NAME= 'Procedure note-Antibiotics administered' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Antibiotics administered';
UPDATE concept_name SET NAME= 'Procedure note-Fluid administered' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Fluid Administered';
UPDATE concept_name SET NAME= 'Procedure note-Fluid amount and unit' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Fluid Amount and Unit';
UPDATE concept_name SET NAME= 'Procedure note-Tourniquet time' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Tourniquet Time';
UPDATE concept_name SET NAME= 'Procedure note-Estimated blood loss' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Estimated Blood Loss';
UPDATE concept_name SET NAME= 'Procedure note-Blood transfusion quantity' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Blood Transfusion Quantity';
UPDATE concept_name SET NAME= 'Procedure note-Findings' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Findings';
UPDATE concept_name SET NAME= 'Procedure note-Intra' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Intra-OP Investigations Ordered';
UPDATE concept_name SET NAME= 'Procedure note-Specimens' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Specimens';
UPDATE concept_name SET NAME= 'Procedure note-Intraoperative meds' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Intraoperative meds';
UPDATE concept_name SET NAME= 'Procedure note-Procedure note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Procedure Note';
UPDATE concept_name SET NAME= 'Procedure note-Complications' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Complications';
UPDATE concept_name SET NAME= 'Transferred to recovery room' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Transferred to recovery room';
UPDATE concept_name SET NAME= 'Extubated operative condition' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Extubated Operative Condition';
UPDATE concept_name SET NAME= 'Stable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stable';
UPDATE concept_name SET NAME= 'Procedure note-Condition' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Condition';
UPDATE concept_name SET NAME= 'Procedure note-Emergency' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Emergency';
UPDATE concept_name SET NAME= 'Procedure note-IPD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, IPD';
UPDATE concept_name SET NAME= 'Procedure note-OPD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, OPD';
UPDATE concept_name SET NAME= 'Procedure note-Direct outside referral' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Direct outside referral';
UPDATE concept_name SET NAME= 'Procedure note-Presented from' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Presented from';
UPDATE concept_name SET NAME= 'Active Knee bending' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Knee, Active knee bending';
UPDATE concept_name SET NAME= 'Quadriceps drill' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Knee, Quadriceps drill';
UPDATE concept_name SET NAME= 'Hamstring-Gastrosoleus strengthening' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Knee, Hamstring-Gastrosoleus strengthening';
UPDATE concept_name SET NAME= 'All' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='All';
UPDATE concept_name SET NAME= 'Physiotherapy-Knee' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Knee';
UPDATE concept_name SET NAME= 'Passive ROM' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Elbow, Passive ROM';
UPDATE concept_name SET NAME= 'Active ROM' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Elbow, Active ROM';
UPDATE concept_name SET NAME= 'All' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='All';
UPDATE concept_name SET NAME= 'Physiotherapy-Elbow' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Elbow';
UPDATE concept_name SET NAME= 'Passive spinal flexion' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Spine, Passive Spinal Flexion';
UPDATE concept_name SET NAME= 'Active and passive spinal flexion' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Spine, Active + Passive Spinal Flexion';
UPDATE concept_name SET NAME= 'Passive spinal extension' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Spine, Passive Spinal Extension';
UPDATE concept_name SET NAME= 'Active and passive spinal extension' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Spine, Active + Passive Spinal Extension';
UPDATE concept_name SET NAME= 'All' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='All';
UPDATE concept_name SET NAME= 'Spine' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Spine';
UPDATE concept_name SET NAME= 'Pendulum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Shoulder, Pendulum';
UPDATE concept_name SET NAME= 'Physiotherapy, Shoulder, ROM' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Shoulder, ROM';
UPDATE concept_name SET NAME= 'All' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='All';
UPDATE concept_name SET NAME= 'Shoulder' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Shoulder';
UPDATE concept_name SET NAME= 'ROM' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Other, ROM';
UPDATE concept_name SET NAME= 'Strengthening' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Other, Strengthening';
UPDATE concept_name SET NAME= 'All' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='All';
UPDATE concept_name SET NAME= 'Physiotherapy-Other' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy, Other';
UPDATE concept_name SET NAME= 'Procedure note-Orthopedic procedure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Orthopedic Procedure';
UPDATE concept_name SET NAME= 'Physiotherapy exercises' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Physiotherapy exercises';
UPDATE concept_name SET NAME= 'Procedure note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes';



UPDATE concept_name SET NAME= 'Diagnosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Diagnosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Referred in' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HIV counselling' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure Note-HIV counselling' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Consent for procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure Note-Consent' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Anesthetist' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Anesthetist' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Preoperative meds' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Preoperative meds' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Surgeons' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Surgeons' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Scrub nurse' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Scrub nurse' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Circulating nurse' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Circulating nurse' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other staff' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedures-Other staff' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cathetrigetion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Cathetrigetion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Dilatation' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Dilatation' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Excision' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Excision' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Figure 8 bandage' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Figure 8 bandage' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Foreign body removal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Foreign body removal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'First time dressing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'First time dressing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'up dressing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Follow-up dressing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Incision and drainage' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Incision and drainage' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Norplant removal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Norplant removal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Retrzetion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Retrzetion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Suture in' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Suture in' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Suture out' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Suture out' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Syringing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Syringing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Orthopedic procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Orthopedic procedure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Other procedure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Procedure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Specific intervention' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Specific intervention' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Above elbow' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Above elbow' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Below elbow' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Below elbow' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Above knee' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Above knee' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Below knee' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Below knee' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Ortho procedure location' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Ortho procedure location' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cast application' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Cast application' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cast adjustment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Cast adjustment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cast removal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Cast removal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Slab application' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Slab application' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Slab removal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Slab removal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Scaphoid cast' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Scaphoid cast' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Thumb spica cast' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Thumb spica cast' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Olecranon brace (ocb)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Olecranon brace (ocb)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Patellar tendon brace (PTB)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Patellar tendon brace (PTB)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Wound inspection' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Wound inspection' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'First time dressing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'First time dressing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Follow-up dressing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Follow-up dressing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'K-wire removal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'K-wire removal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Triangular sling application' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Triangular sling application' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cuff and collar sling application' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Cuff and collar sling application' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'High groin cast' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'High groin cast' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Crepe bandage application' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Crepe bandage application' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cyst removal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Cyst removal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Figure 8 bandage' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Figure 8 bandage' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Foreign body removal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Foreign body removal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Hip spica' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Hip spica' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Other' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Ortho procedure and other' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Local' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Local anesthesia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Regional' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Regional anesthesia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'General' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-General anesthesia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'None' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'None' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Type of anesthesia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Type of anesthesia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Anesthesia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Anesthesia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Antibiotics administered' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Antibiotics administered' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Fluid administered' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Fluid administered' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Fluid amount and unit' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Fluid amount and unit' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Tourniquet time' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Tourniquet time' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Estimated blood loss' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Estimated blood loss' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Blood transfusion quantity' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Blood transfusion quantity' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Findings' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Findings' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Intra-OP investigations ordered' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Intra' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Specimens' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Specimens' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Intraoperative meds' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Intraoperative meds' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Procedure note' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Procedure note' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Complications' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Complications' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Transferred to recovery room' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Transferred to recovery room' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Extubated' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Extubated operative condition' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stable' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Condition' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Condition' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Emergency' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Emergency' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IPD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-IPD' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'OPD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-OPD' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Direct outside referral' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Direct outside referral' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Presented from' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Presented from' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Active knee bending' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Active Knee bending' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Quadriceps drill' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Quadriceps drill' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Hamstring-Gastrosoleus strengthening' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Hamstring-Gastrosoleus strengthening' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'All' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'All' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Knee' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Physiotherapy-Knee' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Passive ROM' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Passive ROM' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Active ROM' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Active ROM' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'All' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'All' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Elbow' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Physiotherapy-Elbow' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Passive spinal flexion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Passive spinal flexion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Active + passive spinal flexion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Active and passive spinal flexion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Passive spinal extension' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Passive spinal extension' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Active + passive spinal extension' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Active and passive spinal extension' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'All' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'All' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Spine' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Spine' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pendulum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pendulum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Physiotherapy, Shoulder, ROM' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Physiotherapy, Shoulder, ROM' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'All' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'All' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Shoulder' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Shoulder' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ROM' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ROM' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Strengthening' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Strengthening' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'All' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'All' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Physiotherapy-Other' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Orthopedic procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Orthopedic procedure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Physiotherapy exercises' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Physiotherapy exercises' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Procedure note' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );