/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR IMAM PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/


UPDATE concept_name SET NAME= 'New' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='New';
UPDATE concept_name SET NAME= 'FP-Users type' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FP, Users Type';
UPDATE concept_name SET NAME= 'FRH-counselling done' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-counselling done';
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred In';
UPDATE concept_name SET NAME= 'FRH-Consent obtained' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Consent Obtained';
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Condoms';
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pills';
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Depo';
UPDATE concept_name SET NAME= 'FRH-short acting method provided' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-short acting method provided';
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Implant';
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='IUCD';
UPDATE concept_name SET NAME= 'Minilap' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Minilap';
UPDATE concept_name SET NAME= 'Vasectomy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Vasectomy';
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Other';
UPDATE concept_name SET NAME= 'FRH-Long acting and permanent method' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Long acting and permanent method';
UPDATE concept_name SET NAME= 'Ring pessary insertion' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Ring Pessary Insertion';
UPDATE concept_name SET NAME= 'PV/PS exam' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PV/PS Exam';
UPDATE concept_name SET NAME= 'FRH-Other procedure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Other procedure';
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Condoms';
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pills';
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Depo';
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Implant';
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='IUCD';
UPDATE concept_name SET NAME= 'FRH-Existing continued' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Existing continued';
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Condoms';
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pills';
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Depo';
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Implant';
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='IUCD';
UPDATE concept_name SET NAME= 'FRH-Discontinued' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Discontinued';
UPDATE concept_name SET NAME= 'FRH-Reason for discontinue' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Reason for discontinue';
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Condoms';
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pills';
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Depo';
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Implant';
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='IUCD';
UPDATE concept_name SET NAME= 'Vasectomy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Vasectomy';
UPDATE concept_name SET NAME= 'Minilap' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Minilap';
UPDATE concept_name SET NAME= 'FRH-New method chosen' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-New method chosen';
UPDATE concept_name SET NAME= 'FRH-Units provided' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Units provided';
UPDATE concept_name SET NAME= 'FRH-Procedure follow up' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Procedure Follow Up';
UPDATE concept_name SET NAME= 'Local anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Local Anesthesia';
UPDATE concept_name SET NAME= 'Procedure Notes-Type of anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure Notes, Type of anesthesia, Regional';
UPDATE concept_name SET NAME= 'General anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='General Anesthesia';
UPDATE concept_name SET NAME= 'FRH-Anesthesia applied' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Anesthesia applied';
UPDATE concept_name SET NAME= 'FRH-Sterile technique' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Sterile Technique';
UPDATE concept_name SET NAME= 'FRH-Complications' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Complications';
UPDATE concept_name SET NAME= 'FRH-Additional findings' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Additional Findings';
UPDATE concept_name SET NAME= 'ANC-Own' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Own';
UPDATE concept_name SET NAME= 'ANC-Kin' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Kin';
UPDATE concept_name SET NAME= 'FRH-Client contact number' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Client contact number';
UPDATE concept_name SET NAME= 'FRH-Contact number' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Contact Number';
UPDATE concept_name SET NAME= 'FRH-Guardian name' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Guardian Name';
UPDATE concept_name SET NAME= 'Relationship-Husband' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Relationship-Husband';
UPDATE concept_name SET NAME= 'Relationship-Family member' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Relationship-Family member';
UPDATE concept_name SET NAME= 'Relationship-Next to kin' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Relationship-Next to Kin';
UPDATE concept_name SET NAME= 'Relationship-Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Relationship-Others';
UPDATE concept_name SET NAME= 'FRH-Guardian relationship' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-Guardian Relationship';
UPDATE concept_name SET NAME= 'FRH-New users' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-New users';
UPDATE concept_name SET NAME= 'FRH-Continuous user' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='FRH-continuous user';
UPDATE concept_name SET NAME= 'Family planning and reproductive health(FRH) note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Family planning and reproductive helath template';


UPDATE concept_name SET NAME= 'New' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'New' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Users type' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FP-Users type' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Counselling done' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-counselling done' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Referred in' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Consent' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Consent obtained' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Condoms' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pills' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Depo' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Short acting method' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-short acting method provided' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Implant' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'IUCD' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Minilap' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Minilap' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Vasectomy' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Vasectomy' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Other' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Long acting methods' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Long acting and permanent method' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Ring pessary insertion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Ring pessary insertion' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'PV/PS exam' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PV/PS exam' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Other procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Other procedure' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Condoms' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pills' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Depo' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Implant' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'IUCD' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Existing continued' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Existing continued' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Condoms' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pills' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Depo' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Implant' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'IUCD' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Discontinued' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Discontinued' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Reason for discontinue' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Reason for discontinue' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Condoms' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Pills' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pills' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Depo' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Implant' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'IUCD' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Vasectomy' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Vasectomy' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Minilap' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Minilap' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'New method chosen' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-New method chosen' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Units provided' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Units provided' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Method effective till' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Procedure follow up' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'LA' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Local anesthesia' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Regional' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure Notes-Type of anesthesia' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'GA' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'General anesthesia' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Anesthesia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Anesthesia applied' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Sterile technique observed' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Sterile technique' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Complications' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Complications' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Additional findings' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Additional findings' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Own' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ANC-Own' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Kin' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ANC-Kin' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Client contact number' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Client contact number' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Number' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Contact number' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Guardian name' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Guardian name' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Husband' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Relationship-Husband' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Family member' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Relationship-Family member' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Next to kin' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Relationship-Next to kin' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Relationship-Others' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Guardian relationship' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Guardian relationship' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'New users' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-New users' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Continuous user' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'FRH-Continuous user' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Family planning and reproductive health' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Family planning and reproductive health(FRH) note' AND concept_name_type='FULLY_SPECIFIED limit 1') a );