/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR IMAM PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/


UPDATE concept_name SET NAME= 'Skilled birth attendant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Skilled Birth Attendant';
UPDATE concept_name SET NAME= 'Non sba health worker' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Non SBA Health worker';
UPDATE concept_name SET NAME= 'Delivery-Delivery service done by' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Delivery service done by';
UPDATE concept_name SET NAME= 'Delivery-Main attendant name' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Main Attendant Name';
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred In';
UPDATE concept_name SET NAME= 'Delivery-Delivery date and time' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Delivery date and time';
UPDATE concept_name SET NAME= 'Systolic' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Systolic';
UPDATE concept_name SET NAME= 'BP Systolic Data-Systolic Abnormal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Congestive Heart Failure - Examination / Follow Up - Physical Examination - BP Systolic Data - Systolic Abnormal';
UPDATE concept_name SET NAME= 'BP Diastolic Data-Diastolic' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Congestive Heart Failure - Examination / Follow Up - Physical Examination - BP Diastolic Data - Diastolic';
UPDATE concept_name SET NAME= 'BP Diastolic Data-Diastolic Abnormal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Congestive Heart Failure - Examination / Follow Up - Physical Examination - BP Diastolic Data - Diastolic Abnormal';
UPDATE concept_name SET NAME= 'Sitting' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Sitting';
UPDATE concept_name SET NAME= 'Supine' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Supine';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'Posture' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Posture';
UPDATE concept_name SET NAME= 'Delivery-Completed 4 anc visits per protocol' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery note-Completed 4 ANC visits per protocol';
UPDATE concept_name SET NAME= 'Delivery-Patient condition at the time of admission' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Patient Condition at the time of admission';
UPDATE concept_name SET NAME= 'Spontaneous vaginal delivery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Spontaneous Vaginal Delivery';
UPDATE concept_name SET NAME= 'Forceps assisted' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Forceps assisted';
UPDATE concept_name SET NAME= 'Vacuum assisted' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Vacuum assisted';
UPDATE concept_name SET NAME= 'Caesarean section' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Caesarean section';
UPDATE concept_name SET NAME= 'Delivery-Method of delivery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Method of Delivery';
UPDATE concept_name SET NAME= 'Single-livebirth' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Single - livebirth';
UPDATE concept_name SET NAME= 'Single-stillbirth' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Single - stillbirth';
UPDATE concept_name SET NAME= 'Twins-both liveborn' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Twins - both liveborn';
UPDATE concept_name SET NAME= 'Twins-both stillborn' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Twins - both stillborn';
UPDATE concept_name SET NAME= 'Twins-one liveborn and one stillborn' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Twins - one liveborn and one stillborn';
UPDATE concept_name SET NAME= 'Other multiple births-all liveborn' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Other multiple births - all liveborn';
UPDATE concept_name SET NAME= 'Other multiple births-some liveborn' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Other multiple births - some liveborn';
UPDATE concept_name SET NAME= 'Other multiple births-all stillborn' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Other multiple births - all stillborn';
UPDATE concept_name SET NAME= 'Delivery-Outcome of delivery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Outcome of Delivery';
UPDATE concept_name SET NAME= 'Not applicable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not Applicable';
UPDATE concept_name SET NAME= 'Fresh stillbirth' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Fresh stillbirth';
UPDATE concept_name SET NAME= 'Macerated' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Macerated';
UPDATE concept_name SET NAME= 'Delivery-Stillbirth type' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Stillbirth type';
UPDATE concept_name SET NAME= 'Delivery-Gestation period' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Gestation period';
UPDATE concept_name SET NAME= 'Cephalic' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cephalic presentation';
UPDATE concept_name SET NAME= 'Shoulder' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Shoulder Presentation';
UPDATE concept_name SET NAME= 'Breech' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Breech presentation';
UPDATE concept_name SET NAME= 'Delivery-Fetal presentation' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Fetal Presentation';
UPDATE concept_name SET NAME= 'Delivery-Meconium stained liquor' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Meconium Stained Liquor';
UPDATE concept_name SET NAME= 'Manual removal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Manual Removal';
UPDATE concept_name SET NAME= 'Chest tightness' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Chest tightness';
UPDATE concept_name SET NAME= 'Delivery-Method of delivery of placenta' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Method of delivery of placenta';
UPDATE concept_name SET NAME= 'Complete' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Complete';
UPDATE concept_name SET NAME= 'Incomplete' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Incomplete';
UPDATE concept_name SET NAME= 'Doubtful' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Doubtful';
UPDATE concept_name SET NAME= 'Delivery-Placenta delivery status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Placenta delivery status';
UPDATE concept_name SET NAME= 'Complete' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Complete';
UPDATE concept_name SET NAME= 'Ragged' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Ragged';
UPDATE concept_name SET NAME= 'Retained' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Retained';
UPDATE concept_name SET NAME= 'Delivery-Membrane condition' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Membrane condition';
UPDATE concept_name SET NAME= 'Herniotomy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Herniotomy';
UPDATE concept_name SET NAME= 'Disarticulation' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Disarticulation';
UPDATE concept_name SET NAME= 'First Degree Perineal Laceration' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='First Degree Perineal Laceration, with Delivery';
UPDATE concept_name SET NAME= 'Second Degree Perineal Laceration' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Second Degree Perineal Laceration, with Delivery';
UPDATE concept_name SET NAME= 'Third Degree Perineal Laceration' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Third Degree Perineal Laceration, with Delivery';
UPDATE concept_name SET NAME= 'Delivery-4th degree laceration' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery note-4th Degree Laceration';
UPDATE concept_name SET NAME= 'Delivery-Perineum condition' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Perineum condition';
UPDATE concept_name SET NAME= 'Delivery-Suturing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Suturing';
UPDATE concept_name SET NAME= 'Prolonged labour' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Prolonged Labour';
UPDATE concept_name SET NAME= 'obstructed labour' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='obstructed labour';
UPDATE concept_name SET NAME= 'Antepartum haemorrhage' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Antepartum Haemorrhage';
UPDATE concept_name SET NAME= 'Ruptured uterus' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Ruptured Uterus';
UPDATE concept_name SET NAME= 'Postpartum haemorrhage' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Postpartum Haemorrhage';
UPDATE concept_name SET NAME= 'Retained placenta' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Retained Placenta';
UPDATE concept_name SET NAME= 'Pueperal sepsis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pueperal Sepsis';
UPDATE concept_name SET NAME= 'Pre eclampsia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pre?Eclampsia';
UPDATE concept_name SET NAME= 'Eclampsia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Eclampsia';
UPDATE concept_name SET NAME= 'RH negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='RH Negative';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not present';
UPDATE concept_name SET NAME= 'Delivery-Complication present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note-Complication Present';
UPDATE concept_name SET NAME= 'Delivery-Anti D provided?' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery note-Anti D provided?';
UPDATE concept_name SET NAME= 'Delivery-Total blood loss' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Total blood loss';
UPDATE concept_name SET NAME= 'Delivery-Blood transfusion quantity' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Blood transfusion quantity';
UPDATE concept_name SET NAME= 'HIV counselled' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIV Counselled';
UPDATE concept_name SET NAME= 'HTC-Tested before' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HTC, Tested before';
UPDATE concept_name SET NAME= 'Delivery-Is women hiv+ve?' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery note-Is women HIV+ve?';
UPDATE concept_name SET NAME= 'Delivery-Test performed in this delivery?' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery note-Test performed in this delivery?';
UPDATE concept_name SET NAME= 'HIV positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIV positive';
UPDATE concept_name SET NAME= 'HIV negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIV negative';
UPDATE concept_name SET NAME= 'Delivery-Test result' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery note-Test result';
UPDATE concept_name SET NAME= 'Infant ip' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Infant IP';
UPDATE concept_name SET NAME= 'Delivery-Other complications' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Other Complications';
UPDATE concept_name SET NAME= 'Delivery-Treatment suggestion' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note, Treatment Suggestion';
UPDATE concept_name SET NAME= 'Delivery-Referred out' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery Note-Referred Out';
UPDATE concept_name SET NAME= 'Yes' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Yes';
UPDATE concept_name SET NAME= 'Not applicable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not Applicable';
UPDATE concept_name SET NAME= 'Delivery-Early neonatal death' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery note, Early Neonatal Death';
UPDATE concept_name SET NAME= 'Systolic data' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Systolic Data';
UPDATE concept_name SET NAME= 'Diastolic data' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Diastolic Data';
UPDATE concept_name SET NAME= 'Blood pressure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Blood Pressure';
UPDATE concept_name SET NAME= 'Delivery-HIV/STI section' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery note-HIV/STI section';
UPDATE concept_name SET NAME= 'Delivery-Mother detail' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery note-Mother Detail';
UPDATE concept_name SET NAME= 'Delivery note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Delivery note';


UPDATE concept_name SET NAME= 'Fresh' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Fresh stillbirth' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Macerated' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Macerated' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Stillbirth type' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Stillbirth type' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Gestation period' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Gestation period' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Cephalic' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Cephalic' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Shoulder' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Shoulder' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Breech' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Breech' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Presentation' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Fetal presentation' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Meconium stained liquor' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Meconium stained liquor' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Manual removal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Manual removal' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Controlled cord traction' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Chest tightness' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Method of delivery of placenta' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Method of delivery of placenta' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Complete' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Complete' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Incomplete' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Incomplete' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Doubtful' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Doubtful' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Placenta delivery status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Placenta delivery status' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Complete' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Complete' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Ragged' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Ragged' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Retained' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Retained' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Membrane condition' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Membrane condition' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Intact' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Herniotomy' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Episiotomy on mother' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Disarticulation' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '1st degree laceration' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'First Degree Perineal Laceration' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '2nd degree laceration' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Second Degree Perineal Laceration' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '3rd degree laceration' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Third Degree Perineal Laceration' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '4th degree laceration' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-4th degree laceration' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Perineum condition' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Perineum condition' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Suturing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Suturing' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Prolonged labour' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Prolonged labour' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'obstructed labour' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'obstructed labour' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Antepartum haemorrhage' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Antepartum haemorrhage' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Ruptured uterus' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Ruptured uterus' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Postpartum haemorrhage' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Postpartum haemorrhage' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Retained placenta' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Retained placenta' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Pueperal sepsis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pueperal sepsis' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Pre eclampsia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pre eclampsia' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Eclampsia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Eclampsia' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'RH negative' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'RH negative' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not present' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Complication present' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Complication present' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Anti D provided?' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Anti D provided?' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Total blood loss (ml)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Total blood loss' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Blood transfusion quantity (pint)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Blood transfusion quantity' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'HIV counselled' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIV counselled' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'HIV tested before' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HTC-Tested before' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Is women hiv+ve?' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Is women hiv+ve?' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'HIV test is this delivery' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Test performed in this delivery?' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'HIV positive' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIV positive' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'HIV negative' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIV negative' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Test result' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Test result' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Infant IP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Infant ip' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Other complications' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Other complications' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Treatment suggestion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Treatment suggestion' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Referral required' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Referred out' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Yes' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Yes' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'NA' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not applicable' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Early neonatal death' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Early neonatal death' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Systolic data' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Systolic data' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Diastolic data' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Diastolic data' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Blood pressure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Blood pressure' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'HIV/STI' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-HIV/STI section' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Mother detail' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery-Mother detail' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= 'Delivery note' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Delivery note' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );
UPDATE concept_name SET NAME= '' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '' AND concept_name_type='FULLY_SPECIFIED limit 1') a );