/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR ANIMAL BITE PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/


UPDATE concept_name SET NAME= 'Animal bite-Dog' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Dog';
UPDATE concept_name SET NAME= 'Animal bite-Cat' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Cat';
UPDATE concept_name SET NAME= 'Animal bite-Wild animal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Wild animal';
UPDATE concept_name SET NAME= 'Animal bite-Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Others';
UPDATE concept_name SET NAME= 'Animal bite-Biting animal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Biting animal';
UPDATE concept_name SET NAME= 'Animal bite-Others(specify)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Others(specify)';
UPDATE concept_name SET NAME= 'Animal bite-Date of bite' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Date of bite';
UPDATE concept_name SET NAME= 'Animal bite-Face/head' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Face/head';
UPDATE concept_name SET NAME= 'Animal bite-Palm/Finger' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Palm/Finger';
UPDATE concept_name SET NAME= 'Animal bite-Hand/forehand' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Hand/forehand';
UPDATE concept_name SET NAME= 'Animal bite-Upper trunk' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Upper trunk';
UPDATE concept_name SET NAME= 'Animal bite-Hand/Arm' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Hand/Arm';
UPDATE concept_name SET NAME= 'Animal bite-Lower trunk' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Lower trunk';
UPDATE concept_name SET NAME= 'Animal bite-Leg' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Leg';
UPDATE concept_name SET NAME= 'Animal bite-Site of bite' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Site of bite';
UPDATE concept_name SET NAME= 'Animal bite-Scratch' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Scratch';
UPDATE concept_name SET NAME= 'Animal bite-Superficial' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Superficial';
UPDATE concept_name SET NAME= 'Animal bite-Multiple wound' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Multiple wound';
UPDATE concept_name SET NAME= 'Animal bite-Deep' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Deep';
UPDATE concept_name SET NAME= 'Animal bite-Type of wound' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Type of wound';
UPDATE concept_name SET NAME= 'Animal bite-Address of the owner or location of the animal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Address of the owner or Location of the animal';
UPDATE concept_name SET NAME= 'Animal bite-Yes' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Yes';
UPDATE concept_name SET NAME= 'Animal bite-No' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-No';
UPDATE concept_name SET NAME= 'Animal bite-Not applicable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Not applicable';
UPDATE concept_name SET NAME= 'Animal bite-Animal vaccinated?' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Animal vaccinated?';
UPDATE concept_name SET NAME= 'Animal bite-Category i' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Category I';
UPDATE concept_name SET NAME= 'Animal bite-Category ii' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Category II';
UPDATE concept_name SET NAME= 'Animal bite-Category iii(encirble)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Category III(Encirble)';
UPDATE concept_name SET NAME= 'Animal bite-Category of bite' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Category of bite';
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred In';
UPDATE concept_name SET NAME= 'Animal bite-Cat/Dog' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Cat/Dog-Domestic';
UPDATE concept_name SET NAME= 'Animal bite-Cat/Dog' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Cat/Dog-stray, Wild';
UPDATE concept_name SET NAME= 'Animal bite-Type of animal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Type of animal';
UPDATE concept_name SET NAME= 'Animal bite-Possible/Confirmed' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Possible/Confirmed';
UPDATE concept_name SET NAME= 'Animal bite-Not (possible/confirmed)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Not (Possible/Confirmed)';
UPDATE concept_name SET NAME= 'Animal bite-Observation/Identification' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Observation/Identification';
UPDATE concept_name SET NAME= 'Animal bite-2 consecutive in last two years & one within 1 yr.' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-2 consecutive in last two years & one within 1 yr.';
UPDATE concept_name SET NAME= 'Animal bite-No or not applicable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-No or Not applicable';
UPDATE concept_name SET NAME= 'Animal bite-Vaccination' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Vaccination';
UPDATE concept_name SET NAME= 'Animal bite-Provoked bite' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Provoked bite';
UPDATE concept_name SET NAME= 'Animal bite-Normal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Normal';
UPDATE concept_name SET NAME= 'Animal bite-Suspecious' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Suspecious';
UPDATE concept_name SET NAME= 'Animal bite-Behavior' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Behavior';
UPDATE concept_name SET NAME= 'Animal bite-Tetanus texoid' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Tetanus texoid';
UPDATE concept_name SET NAME= 'Animal bite-Anti rabies vaccine' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Anti rabies vaccine';
UPDATE concept_name SET NAME= 'Animal bite-Not applicable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Not applicable';
UPDATE concept_name SET NAME= 'Animal bite-Vaccination provided' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Vaccination provided';
UPDATE concept_name SET NAME= 'Animal bite-Day 0' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Day 0';
UPDATE concept_name SET NAME= 'Animal bite-Day 7' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Day 7';
UPDATE concept_name SET NAME= 'Animal bite-Day 21' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Day 21';
UPDATE concept_name SET NAME= 'Animal bite-Day 28' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Day 28';
UPDATE concept_name SET NAME= 'Animal bite-Not applicable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Not applicable-prophylaxis';
UPDATE concept_name SET NAME= 'Animal bite-Pre exposure prophylaxis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Pre exposure prophylaxis';
UPDATE concept_name SET NAME= 'Animal bite-Day 0' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Day 0';
UPDATE concept_name SET NAME= 'Animal bite-Day 3' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Day 3';
UPDATE concept_name SET NAME= 'Animal bite-Day 7' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Day 7';
UPDATE concept_name SET NAME= 'Animal bite-Day 14' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Day 14';
UPDATE concept_name SET NAME= 'Animal bite-Day 28' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Day 28';
UPDATE concept_name SET NAME= 'Animal bite-Not applicable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Not applicable';
UPDATE concept_name SET NAME= 'Animal bite-Post exposure treatment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Post exposure treatment';
UPDATE concept_name SET NAME= 'Animal bite-Name of the service provider' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Name of the service provider';
UPDATE concept_name SET NAME= 'Animal bite-History of animal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-History of Animal';
UPDATE concept_name SET NAME= 'Animal bite-Treatment (only for PCEC)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease-Treatment (only for PCEC)';
UPDATE concept_name SET NAME= 'Animal bite note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zoonotic Disease';



UPDATE concept_name SET NAME= 'Dog' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Dog' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cat' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Cat' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Wild animal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Wild animal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Biting animal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Biting animal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others(specify)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Others(specify)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Date of bite' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Date of bite' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Face/head' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Face/head' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Palm/Finger' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Palm/Finger' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Hand/forehand' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Hand/forehand' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Upper trunk' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Upper trunk' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Hand/Arm' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Hand/Arm' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Lower trunk' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Lower trunk' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Leg' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Leg' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Site of bite' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Site of bite' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Scratch' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Scratch' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Superficial' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Superficial' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Multiple wound' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Multiple wound' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Deep' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Deep' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Type of wound' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Type of wound' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Address of the owner or location of the animal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Address of the owner or location of the animal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Yes' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Yes' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'No' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-No' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'N/A' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Not applicable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Animal vaccinated?' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Animal vaccinated?' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category i' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Category i' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category ii' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Category ii' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category iii(encirble)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Category iii(encirble)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category of bite' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Category of bite' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Referred in' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cat/Dog-Domestic' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Cat/Dog' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cat/Dog-stray' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Cat/Dog' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Type of animal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Type of animal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Possible/Confirmed' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Possible/Confirmed' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Not (possible/confirmed)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Not (possible/confirmed)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Observation/Identification' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Observation/Identification' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '2 consecutive in last two years & one within 1 yr.' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-2 consecutive in last two years & one within 1 yr.' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'No or not applicable' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-No or not applicable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Vaccination' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Vaccination' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Provoked bite' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Provoked bite' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Normal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Normal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Suspeciuos' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Suspecious' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Behavior' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Behavior' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TT' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Tetanus texoid' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ARV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Anti rabies vaccine' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'N/A' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Not applicable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Vaccination provided' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Vaccination provided' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Day 0' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Day 0' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Day 7' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Day 7' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Day 21' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Day 21' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Day 28' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Day 28' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'N/A' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Not applicable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pre exposure prophylaxis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Pre exposure prophylaxis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Day 0' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Day 0' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Day 3' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Day 3' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Day 7' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Day 7' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Day 14' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Day 14' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Day 28' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Day 28' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'N/A' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Not applicable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Post exposure treatment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Post exposure treatment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Name of the service provider' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Name of the service provider' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'History of animal (for cat/dog only)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-History of animal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Treatment (only for PCEC)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite-Treatment (only for PCEC)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Animal bite' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Animal bite note' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );