/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR CBIMNCI 2 - 59 MONTHS PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/


UPDATE concept_name SET NAME= 'New' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='New';
UPDATE concept_name SET NAME= 'Follow-up visit' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Follow-up Visit';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Case' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness-2 to 59 months-Case';
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred In';
UPDATE concept_name SET NAME= 'OPD-Chief complaint' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Out Patient Details, Chief Complaint';
UPDATE concept_name SET NAME= 'OPD-HPI notes' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Out Patient Details, HPI Notes';
UPDATE concept_name SET NAME= 'OPD-Physical examination details' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Out Patient Details, Physical Examination Details';
UPDATE concept_name SET NAME= 'Respiratory Rate 2-1 years' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Respiratory Rate 2-1 Years';
UPDATE concept_name SET NAME= 'Respiratory rate abnormal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Respiratory Rate Abnormal';
UPDATE concept_name SET NAME= 'Respiratory Rate 1-5 years' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Respiratory Rate 1-5 Years';
UPDATE concept_name SET NAME= 'Respiratory rate abnormal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Respiratory Rate Abnormal';
UPDATE concept_name SET NAME= 'Childhood Illness-Temperature' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Temperature';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-General danger signs present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, General Danger Signs present';
UPDATE concept_name SET NAME= 'Chest indrawing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Chest indrawing';
UPDATE concept_name SET NAME= 'Strider' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Strider';
UPDATE concept_name SET NAME= 'Wheezing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Wheezing';
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not present';
UPDATE concept_name SET NAME= 'Acute Respiratory Illness-Symptoms' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Acute Respiratory Illness, Symptoms';
UPDATE concept_name SET NAME= 'Acute Respiratory Illness-Days' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Acute Respiratory Illness, Days';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-No pneumonia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-ARI-Classification-No pneumonia';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Pneumonia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-ARI-Classification-Pneumonia';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Severe pneumonia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-ARI-Classification-Severe Pneumonia';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-ARI classification' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-ARI-Classification';
UPDATE concept_name SET NAME= 'Diarrhea' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Diarrhea';
UPDATE concept_name SET NAME= 'Chronic diarrhea' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Chronic Diarrhea';
UPDATE concept_name SET NAME= 'Dysentery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness - Diarrhea - Dysentery';
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not present';
UPDATE concept_name SET NAME= 'Childhood Illness-Diarrhoea present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Diarrhoea present';
UPDATE concept_name SET NAME= 'Slowly' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Slowly';
UPDATE concept_name SET NAME= 'Very slowly' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Very Slowly';
UPDATE concept_name SET NAME= 'Skin pinch' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Diarrhoea, Skin pinch';
UPDATE concept_name SET NAME= 'No dehydration' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='No Dehydration';
UPDATE concept_name SET NAME= 'Some dehydration' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Some Dehydration';
UPDATE concept_name SET NAME= 'Severe dehydration' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Severe Dehydration';
UPDATE concept_name SET NAME= 'Not applicable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not Applicable';
UPDATE concept_name SET NAME= 'Childhood Illness-Dehydration status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Dehydration Status';
UPDATE concept_name SET NAME= 'Childhood Illness-Fever present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Fever present';
UPDATE concept_name SET NAME= 'Days of fever' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Fever, Days';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Nature of fever' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Fever-Nature of Fever';
UPDATE concept_name SET NAME= 'High' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='High';
UPDATE concept_name SET NAME= 'Low' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Low';
UPDATE concept_name SET NAME= 'Very low' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Very low';
UPDATE concept_name SET NAME= 'Risk free' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Risk free';
UPDATE concept_name SET NAME= 'Stratified malaria risk' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stratified Malaria risk';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Complicated malaria' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Risk Zone-Complicated Malaria';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Falciparum malaria' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Risk Zone-Falciparum Malaria';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Non falciparum malaria' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Risk Zone-Non Falciparum Malaria';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Fever without malaria' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Risk Zone-Fever without malaria';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Other cause of fever' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Free Zone-Other causes of fever';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Measles' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Free Zone-Measles';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Measles in last 3 months' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Free Zone-Measles in last 3 months';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Severe complicated measles' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Free Zone-Severe Complicated Measles';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Measles with opthalmic complication' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Free Zone-Measles with oral or opthalmic complication';
UPDATE concept_name SET NAME= 'Ear pain' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Ear pain';
UPDATE concept_name SET NAME= 'Tender swelling behind the ear' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Tender swelling behind the ear';
UPDATE concept_name SET NAME= 'Ear discharge' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Ear discharge';
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not present';
UPDATE concept_name SET NAME= 'Ear infections symptoms' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Ear infections, Symptoms';
UPDATE concept_name SET NAME= 'Ear discharge days' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Ear discharge, Days';
UPDATE concept_name SET NAME= 'Ear infection days' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Ear infection, Days';
UPDATE concept_name SET NAME= 'Acute ear infection' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Ear Infection-Acute Ear Infection';
UPDATE concept_name SET NAME= 'Chronic ear infection' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Ear Infection-Chronic Ear Infection';
UPDATE concept_name SET NAME= 'Mastoiditis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Ear Infection-Mastoiditis';
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not present';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Ear infection present' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Ear Infection present';
UPDATE concept_name SET NAME= 'Normal weight' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Normal weight';
UPDATE concept_name SET NAME= 'Low weight' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Low weight';
UPDATE concept_name SET NAME= 'Very low weight' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Very low weight';
UPDATE concept_name SET NAME= 'CBIMNC 2_59-Weight condition' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Weight condition';
UPDATE concept_name SET NAME= 'Some' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Some';
UPDATE concept_name SET NAME= 'Severe' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Nutrition status, Severe';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Pallor' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Nutrition Status, Pallor';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Anaemia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='CBIMNCI-Anaemia';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Other diagnosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness-Nutrition status-Other diagnosis';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-If other diagnosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness-Nutrition status-If other diagnosis';
UPDATE concept_name SET NAME= 'Childhood Illness-Counseling provided' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Counseling provided';
UPDATE concept_name SET NAME= 'Regular follow up' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Regular follow up';
UPDATE concept_name SET NAME= 'Immediate visit' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Immediate visit';
UPDATE concept_name SET NAME= 'Food' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Food';
UPDATE concept_name SET NAME= 'Operative fluids' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Operative Fluids';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Counseling purpose' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, 5years, Counseling purpose';
UPDATE concept_name SET NAME= 'Childhood Illness-Vitamin A  provided' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Vitamin A Capsules Provided';
UPDATE concept_name SET NAME= 'ARI' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Counseling-Refer Out-ARI';
UPDATE concept_name SET NAME= 'Diarrhoea ' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Diarrhoea Opportunistic Infection';
UPDATE concept_name SET NAME= 'Fever' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Fever';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'Malnutrition' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Malnutrition';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Refered out' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Refered-Out';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Advised for OTP/local health facility' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Follow up advised for OTP/local health facility';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Others';
UPDATE concept_name SET NAME= 'Follow up days at BH' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Follow up days at BH';
UPDATE concept_name SET NAME= 'Worse' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Worse';
UPDATE concept_name SET NAME= 'Same' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Same';
UPDATE concept_name SET NAME= 'Improved' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Improved';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Follow up result' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness-2 to 59 months-Follow up result';
UPDATE concept_name SET NAME= 'Childhood Illness-Assessment/plan' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness-Assessment/plan';
UPDATE concept_name SET NAME= 'Amoxicillin' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Amoxicillin';
UPDATE concept_name SET NAME= 'IV fluid' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='IV Fluid';
UPDATE concept_name SET NAME= 'Anti helminthes' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anti-helminthes';
UPDATE concept_name SET NAME= 'Retinol (vitamin A)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Retinol (Vitamin A)';
UPDATE concept_name SET NAME= 'ORS and Zinc' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ORS and Zinc';
UPDATE concept_name SET NAME= 'ORS only' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ORS only';
UPDATE concept_name SET NAME= 'Childhood illness-Other antibiotics' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness - Treatment - Treated with - Other Antibiotics';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Treated with' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness - Treatment - Treated with 2-59';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Respiratory rate data' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness-Respiratory Rate Data';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Acute respiratory infection' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Acute Respiratory Infection';
UPDATE concept_name SET NAME= 'Childhood illness-Diarrhoea' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Diarrhoea';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Fever' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Fever';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Malaria risk zone' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Risk Zone';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Malaria free zone' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness (2-59)-Malaria Free Zone';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Ear infection' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Ear infection';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Nutrition status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Nutrition status';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Counselling' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, 5years, Counseling';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Treatment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness, Treatment 2-59';
UPDATE concept_name SET NAME= 'CBIMNCI (2 to 59 months child)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='CBIMNCI (2 to 59 months child)';
UPDATE concept_name SET NAME= 'Childhood illness-Diarrhoea'  WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness,  Diarrhoea';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Acute respiratory infection' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness,  Acute Respiratory Infection';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Fever' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness,  Fever';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Ear infection' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness,  Ear infection';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Nutrition status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness,  Nutrition status';
UPDATE concept_name SET NAME= 'CBIMNCI 2 to 59-Counselling' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Childhood Illness,  5years, Counseling';




UPDATE concept_name SET NAME= 'New' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'New' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Follow up visit' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Follow-up visit' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Case' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Case' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Referred in' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Chief complaint' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OPD-Chief complaint' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'History of present illness' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OPD-HPI notes' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Physical examination details' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OPD-Physical examination details' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '1 years' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Respiratory Rate 2-1 years' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Respiratory rate abnormal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Respiratory rate abnormal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '5 years' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Respiratory Rate 1-5 years' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Respiratory rate abnormal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Respiratory rate abnormal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Temperature' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Childhood Illness-Temperature' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'General danger signs present' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-General danger signs present' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Chest indrawing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Chest indrawing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Strider' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Strider' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Wheezing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Wheezing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not present' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Symptoms' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Acute Respiratory Illness-Symptoms' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Days' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Acute Respiratory Illness-Days' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'No pneumonia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-No pneumonia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pneumonia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Pneumonia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Severe pneumonia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Severe pneumonia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ARI classification' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-ARI classification' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diarrhea' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Diarrhea' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Chronic diarrhea' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Chronic diarrhea' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Dysentery' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Dysentery' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not present' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diarrhoea present' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Childhood Illness-Diarrhoea present' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Slowly' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Slowly' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Very slowly' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Very slowly' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Skin pinch' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Skin pinch' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'No dehydration' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'No dehydration' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Some dehydration' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Some dehydration' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Severe dehydration' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Severe dehydration' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Not applicable' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not applicable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Dehydration status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Childhood Illness-Dehydration status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Fever present' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Childhood Illness-Fever present' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'How many days?' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Days of fever' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Nature of fever' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Nature of fever' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'High' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'High' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Low' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Low' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Very low' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Very low' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Risk free' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Risk free' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stratified malaria risk' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stratified malaria risk' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Complicated malaria' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Complicated malaria' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Falciparum malaria' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Falciparum malaria' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Non falciparum malaria' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Non falciparum malaria' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Fever without malaria' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Fever without malaria' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other cause of fever' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Other cause of fever' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Measles' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Measles' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Measles in last 3 months' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Measles in last 3 months' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Severe complicated measles' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Severe complicated measles' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Measles with opthalmic complication' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Measles with opthalmic complication' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Ear pain' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Ear pain' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Tender swelling behind the ear' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Tender swelling behind the ear' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Ear discharge' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Ear discharge' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not present' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Symptoms' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Ear infections symptoms' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Days' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Ear discharge days' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Days' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Ear infection days' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Acute ear infection' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Acute ear infection' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Chronic ear infection' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Chronic ear infection' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Mastoiditis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Mastoiditis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Not present' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not present' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Ear infection present' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Ear infection present' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Normal weight' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Normal weight' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Low weight' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Low weight' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Very low weight' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Very low weight' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Weight condition' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNC 2_59-Weight condition' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Some' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Some' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Severe' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Severe' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pallor' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Pallor' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Anaemia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Anaemia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other diagnosis than above' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Other diagnosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'If other diagnosis, specify' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-If other diagnosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Counseling provided' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Childhood Illness-Counseling provided' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Regular follow up' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Regular follow up' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Immediate visit' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Immediate visit' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Food' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Food' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Operative fluids' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Operative fluids' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Counseling purpose' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Counseling purpose' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Vitamin A  provided' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Childhood Illness-Vitamin A  provided' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ARI' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ARI' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diarrhoea ' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Diarrhoea ' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Fever' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Fever' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Malnutrition' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Malnutrition' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Refered out' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Refered out' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Follow up advised for OTP/local health facility' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Advised for OTP/local health facility' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Follow up days at BH' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Follow up days at BH' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Worse' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Worse' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Same' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Same' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Improved' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Improved' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Follow up result' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Follow up result' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Assessment/plan' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Childhood Illness-Assessment/plan' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Amoxicillin' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Amoxicillin' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IV fluid' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'IV fluid' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Anti helminthes' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anti helminthes' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Retinol (vitamin A)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Retinol (vitamin A)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ORS and Zinc' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ORS and Zinc' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ORS only' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ORS only' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other antibiotics' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Childhood illness-Other antibiotics' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Treated with' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Treated with' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Respiratory rate data' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Respiratory rate data' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Acute respiratory infection' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Acute respiratory infection' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diarrhoea' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Childhood illness-Diarrhoea' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Fever' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Fever' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Malaria risk zone' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Malaria risk zone' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Malaria free zone' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Malaria free zone' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Ear infection' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Ear infection' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Nutrition status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Nutrition status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Counselling' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Counselling' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Treatment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI 2 to 59-Treatment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CBIMNCI (2 to 59 months child)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'CBIMNCI (2 to 59 months child)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );