/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR DR TB INTAKE PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Private health facility' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Category II' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Implant' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = '2 weeks' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = '1 month' ;


UPDATE concept_name SET NAME= 'ART-Pre ART number' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ART, Pre-ART Number';
UPDATE concept_name SET NAME= 'ART-ART number' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ART, ART Number';
UPDATE concept_name SET NAME= 'HIVTC-Chief complaint' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Chief Complaint';
UPDATE concept_name SET NAME= 'HIVTC-History of present illness' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, History of Present Illness';
UPDATE concept_name SET NAME= 'HIVTC-Physical examination details' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Physical Examination Details';
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Referred in';
UPDATE concept_name SET NAME= 'HIVTC-Problem' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Problem';
UPDATE concept_name SET NAME= 'Unmarried' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Unmarried';
UPDATE concept_name SET NAME= 'Married' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Married';
UPDATE concept_name SET NAME= 'Divorced' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Divorced';
UPDATE concept_name SET NAME= 'Widowed' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Widowed';
UPDATE concept_name SET NAME= 'HIVTC-Marital status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Marital Status';
UPDATE concept_name SET NAME= 'ART-Patient contact number' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ART, Patient Contact Number';
UPDATE concept_name SET NAME= 'ANC-Own' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Own';
UPDATE concept_name SET NAME= 'ANC-Kin' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ANC-Kin';
UPDATE concept_name SET NAME= 'HIVTC Intake-Whose' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC Intake-Whose';
UPDATE concept_name SET NAME= 'HIVTC Intake-Gurdian Kin name' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC Intake-Gurdian/Kin Name';
UPDATE concept_name SET NAME= 'Sex worker' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Sex worker';
UPDATE concept_name SET NAME= 'People who inject drugs' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='People who inject drugs';
UPDATE concept_name SET NAME= 'MSM and transgenders' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='MSM and transgenders';
UPDATE concept_name SET NAME= 'Blood or organ recipient' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Blood or organ recipient';
UPDATE concept_name SET NAME= 'Client of sex worker' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Client of sex worker';
UPDATE concept_name SET NAME= 'Migrant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Migrant';
UPDATE concept_name SET NAME= 'Spouse of migrant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Spouse of migrant';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC-Risk group' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Risk Group';
UPDATE concept_name SET NAME= 'HTC' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HTC';
UPDATE concept_name SET NAME= 'Tuberculosis entry point' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Tuberculosis Entry Point';
UPDATE concept_name SET NAME= 'Outpatient' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Outpatient';
UPDATE concept_name SET NAME= 'Inpatient' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Inpatient';
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Paediatric';
UPDATE concept_name SET NAME= 'Prevention of Mother to child transmission' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Prevention of Mother-to-child Transmission';
UPDATE concept_name SET NAME= 'Sextually transmitted infection' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Sextually Transmitted Infection';
UPDATE concept_name SET NAME= 'Private health facility' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Private health facility';
UPDATE concept_name SET NAME= 'Non-governmental organization' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Non-governmental Organization';
UPDATE concept_name SET NAME= 'Self referred' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Self Referred';
UPDATE concept_name SET NAME= 'Outreach or special services' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Outreach/Special Services';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC-Entry point' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Entry Point';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/LPV/r';
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/LPV/r';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC-Mothers ARV regimen' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Mothers ARV Regimen';
UPDATE concept_name SET NAME= 'HIVTC-Mothers ARV regimen start date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Mothers ARV Regimen Start Date';
UPDATE concept_name SET NAME= 'HIVTC Intake-Within six weeks' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC Intake-Within six weeks';
UPDATE concept_name SET NAME= 'HIVTC Intake-Six weeks to two months' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC Intake-Six weeks to two months';
UPDATE concept_name SET NAME= '2 to 9 months' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='2 to 9 months';
UPDATE concept_name SET NAME= '9 to 18 months' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='9 to 18 months';
UPDATE concept_name SET NAME= 'ART-Early infant diagnosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ART, Early Infant Diagnosis';
UPDATE concept_name SET NAME= 'ART-PCR test date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ART, PCR Test Date';
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Positive';
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Negative';
UPDATE concept_name SET NAME= 'HIVTC Intake-PCR test result' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC Intake-PCR test result';
UPDATE concept_name SET NAME= 'ART-Antibody test date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ART, Antibody test date';
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Positive';
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Negative';
UPDATE concept_name SET NAME= 'ART-Antibody test result' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ART, Antibody test result';
UPDATE concept_name SET NAME= 'ART-CPT prophylaxis start date after 6wks' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ART, CPT Prophylaxis start date after 6wks';
UPDATE concept_name SET NAME= 'HIVTC-HIV +ve diagnosed date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, HIV +ve diagnosed date';
UPDATE concept_name SET NAME= 'HIVTC-HIV care enrolled date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, HIV care enrolled date';
UPDATE concept_name SET NAME= 'Stage I' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stage I';
UPDATE concept_name SET NAME= 'Stage II' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stage II';
UPDATE concept_name SET NAME= 'Stage III' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stage III';
UPDATE concept_name SET NAME= 'Stage IV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stage IV';
UPDATE concept_name SET NAME= 'HIVTC-HIV care WHO staging' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, HIV care WHO Staging';
UPDATE concept_name SET NAME= 'HIVTC-HIV care CPT started' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, HIV care CPT started';
UPDATE concept_name SET NAME= 'HIVTC-HIV care CPT start date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, HIV care CPT start date';
UPDATE concept_name SET NAME= 'HIVTC-HIV care IPT started' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, HIV care IPT started';
UPDATE concept_name SET NAME= 'HIVTC-HIV care IPT start date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, HIV care IPT start date';
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Negative';
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Positive';
UPDATE concept_name SET NAME= 'HIVTC-Smear TB assessment at enrollment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Smear TB assessment at enrollment';
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Negative';
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Positive';
UPDATE concept_name SET NAME= 'HIVTC-Culture TB assessment at enrollment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Culture TB assessment at enrollment';
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Negative';
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Positive';
UPDATE concept_name SET NAME= 'HIVTC-Chest X ray TB assessment at enrollment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Chest X-Ray TB assessment at enrollment';
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Negative';
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Positive';
UPDATE concept_name SET NAME= 'HIVTC-Gene xpert TB assessment at enrollment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Gene Xpert TB assessment at enrollment';
UPDATE concept_name SET NAME= 'Extra pulmonary' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Extra pulmonary';
UPDATE concept_name SET NAME= 'Pulmonary(BC)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pulmonary(BC)';
UPDATE concept_name SET NAME= 'Pulmonary(CD)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pulmonary(CD)';
UPDATE concept_name SET NAME= 'HIVTC-TB type' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, TB Type';
UPDATE concept_name SET NAME= 'HIVTC-TB treatment start date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, TB Treatment start date';
UPDATE concept_name SET NAME= 'Category I' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Category I';
UPDATE concept_name SET NAME= 'Category II' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Category II';
UPDATE concept_name SET NAME= 'Category III' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Category III';
UPDATE concept_name SET NAME= 'HIVTC-TB regimen' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, TB Regimen';
UPDATE concept_name SET NAME= 'Cured' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cured';
UPDATE concept_name SET NAME= 'Completed' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Completed';
UPDATE concept_name SET NAME= 'Failure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Failure';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC-TB treatment outcome' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, TB Treatment Outcome';
UPDATE concept_name SET NAME= 'HIVTC-Other chronic diseases' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Other chronic diseases';
UPDATE concept_name SET NAME= 'HIVTC-Other chronic disease drugs' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Other chronic disease drugs';
UPDATE concept_name SET NAME= 'HIVTC-ART eligible date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, ART eligible date';
UPDATE concept_name SET NAME= 'HIVTC-ART start date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, ART start date';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/LPV/r';
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/LPV/r';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC-ART regimen' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, ART Regimen';
UPDATE concept_name SET NAME= 'HIVTC-Transferred in from' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Transferred in from';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/LPV/r';
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/LPV/r';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC-Transferred patient regimen' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Transferred Patient Regimen';
UPDATE concept_name SET NAME= 'HIVTC-Date of transferred in' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Date of transferred in';
UPDATE concept_name SET NAME= 'HIVTC-Viral load' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Viral Load';
UPDATE concept_name SET NAME= 'HIVTC-Viral load date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Viral Load date';
UPDATE concept_name SET NAME= 'HIVTC-CD4 count' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, CD4 count';
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Condoms';
UPDATE concept_name SET NAME= 'Oral contraceptives' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Oral Contraceptives';
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='IUCD';
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Depo';
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Implant';
UPDATE concept_name SET NAME= 'Permanent' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Permanent';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC intake-FP chosen' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC intake-FP chosen';
UPDATE concept_name SET NAME= 'HIVTC intake-Consent for home visit' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC intake-Consent for home visit';
UPDATE concept_name SET NAME= '1 week' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='1 week';
UPDATE concept_name SET NAME= '2 weeks' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='2 weeks';
UPDATE concept_name SET NAME= '3 weeks' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='3 weeks';
UPDATE concept_name SET NAME= '1 month' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='1 month';
UPDATE concept_name SET NAME= 'Followup' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Followup';
UPDATE concept_name SET NAME= 'HIVTC intake-Assessment and Plan' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Assessment and Plan';
UPDATE concept_name SET NAME= 'HIVTC intake-Mother ARV regimen details' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Mothers ARV Regimen Details';
UPDATE concept_name SET NAME= 'ART-Antibody test after 18m' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ART, Antibody test after 18m';
UPDATE concept_name SET NAME= 'ART-HIV exposed baby' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ART, HIV Exposed Baby';
UPDATE concept_name SET NAME= 'HIVTC intake-HIV care history intake' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, HIV Care History Intake';
UPDATE concept_name SET NAME= 'HIVTC intake-TB assessment at enrollment in HIV Care' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, TB assessment at the time of Enrollment in HIV Care';
UPDATE concept_name SET NAME= 'HIVTC intake-History of TB' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, History of TB';
UPDATE concept_name SET NAME= 'HIVTC intake- History of other chronic illness' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, History of Other Chronic Illness';
UPDATE concept_name SET NAME= 'HIVTC intake-ART eligibility' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, ART Eligibility';
UPDATE concept_name SET NAME= 'HIVTC intake-Transferred in' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Transferred in';
UPDATE concept_name SET NAME= 'HIV Treatment and care(HIVTC) intake note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIV Treatment and Care Intake Template';

UPDATE concept_name SET NAME= 'Pre-ART number' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ART-Pre ART number' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART number' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ART-ART number' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Chief complaint' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Chief complaint' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'History of present illness' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-History of present illness' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Physical examination details' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Physical examination details' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Referred in' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Referred in' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Problem' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Problem' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Unmarried' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Unmarried' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Married' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Married' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Divorced' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Divorced' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Widowed' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Widowed' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Marital status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Marital status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Contact number' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ART-Patient contact number' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Own' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ANC-Own' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Kin' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ANC-Kin' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Whose?' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC Intake-Whose' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Gurdian/Kin name' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC Intake-Gurdian Kin name' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Sex worker' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Sex worker' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'People who inject drugs' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'People who inject drugs' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'MSM and transgenders' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'MSM and transgenders' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Blood or organ recipient' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Blood or organ recipient' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Client of sex worker' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Client of sex worker' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Migrant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Migrant' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Spouse/Partner of migrant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Spouse of migrant' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Risk group' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Risk group' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HTC' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HTC' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Tuberculosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Tuberculosis entry point' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Outpatient' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Outpatient' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Inpatient' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Inpatient' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'PMTCT' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Prevention of Mother to child transmission' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'STI' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Sextually transmitted infection' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Private health facility' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Private health facility' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'NGO' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Non-governmental organization' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Self referred' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Self referred' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Outreach/Special services' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Outreach or special services' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Entry point' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Entry point' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/NVP-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/EFV-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/NVP-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/EFV-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Regimen' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Mothers ARV regimen' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Regimen start date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Mothers ARV regimen start date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Birth to six weeks' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC Intake-Within six weeks' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '6 weeks to 2 months' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC Intake-Six weeks to two months' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '2 - 9 months' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '2 to 9 months' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '9 - 18 months' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '9 to 18 months' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Early infant diagnosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ART-Early infant diagnosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'PCR test date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ART-PCR test date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Positive' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Negative' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'PCR test result' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC Intake-PCR test result' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Antibody test date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ART-Antibody test date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Positive' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Negative' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Antibody test result' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ART-Antibody test result' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CPT prophylaxis start date after 6wks' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ART-CPT prophylaxis start date after 6wks' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HIV +ve diagnosed date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-HIV +ve diagnosed date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Enrolled date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-HIV care enrolled date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'I' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stage I' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'II' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stage II' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'III' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stage III' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stage IV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'WHO staging' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-HIV care WHO staging' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CPT started' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-HIV care CPT started' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CPT start date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-HIV care CPT start date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IPT started' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-HIV care IPT started' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IPT start date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-HIV care IPT start date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Negative' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Positive' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Smear' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Smear TB assessment at enrollment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Negative' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Positive' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Culture' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Culture TB assessment at enrollment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Negative' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Positive' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Chest x-ray at enrollment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Chest X ray TB assessment at enrollment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Negative' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Positive' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Gene xpert' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Gene xpert TB assessment at enrollment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Extra pulmonary' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Extra pulmonary' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pulmonary(BC)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pulmonary(BC)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pulmonary(CD)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pulmonary(CD)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TB type' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-TB type' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TB treatment start date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-TB treatment start date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category I' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Category I' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category II' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Category II' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category III' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Category III' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TB regimen' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-TB regimen' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cured' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Cured' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Completed' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Completed' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Failure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Failure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Treatment outcome' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-TB treatment outcome' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diseases' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Other chronic diseases' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Drugs' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Other chronic disease drugs' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART eligible date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-ART eligible date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART start date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-ART start date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/NVP-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/EFV-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/NVP-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/EFV-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART regimen' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-ART regimen' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'From (site)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Transferred in from' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/NVP-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/EFV-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/NVP-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/EFV-Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Patient regimen' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Transferred patient regimen' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Transferred in date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Date of transferred in' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Viral load' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Viral load' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Viral load date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-Viral load date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CD4 count' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC-CD4 count' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Condoms' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Oral contraceptives' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Oral contraceptives' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'IUCD' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Depo' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Implant' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Permanent' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Permanent' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'FP chosen' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC intake-FP chosen' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Would you like to participate in home visit service?' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC intake-Consent for home visit' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '1 week' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '1 week' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '2 weeks' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '2 weeks' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '3 weeks' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '3 weeks' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '1 month' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '1 month' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Followup' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Followup' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Assessment and Plan' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC intake-Assessment and Plan' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Mother\'s ARV regimen details' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC intake-Mother ARV regimen details' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Antibody test after 18m' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ART-Antibody test after 18m' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HIV exposed baby' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ART-HIV exposed baby' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HIV care history intake' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC intake-HIV care history intake' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TB assessment at the time of enrollment in HIV Care' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC intake-TB assessment at enrollment in HIV Care' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'History of TB' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC intake-History of TB' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'History of other chronic illness' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC intake- History of other chronic illness' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART eligibility' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC intake-ART eligibility' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Transferred in' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC intake-Transferred in' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HIV Treatment and care intake note' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIV Treatment and care(HIVTC) intake note' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );