/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR DR TB INTAKE PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'On Treatment' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Implant' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Improved' ;


UPDATE concept_name SET NAME= 'Self' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Self';
UPDATE concept_name SET NAME= 'HIVTC FU-Other or relatives' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC-Other/Relatives';
UPDATE concept_name SET NAME= 'HIVTC FU-Visit' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC-Visit';
UPDATE concept_name SET NAME= 'HIVTC FU-Chief complaint' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Chief Complaint';
UPDATE concept_name SET NAME= 'HIVTC FU-Physical examination details' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Physical Examination Details';
UPDATE concept_name SET NAME= 'HIVTC FU-History of present illness' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, History of Present Illness';
UPDATE concept_name SET NAME= 'Zero' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Zero';
UPDATE concept_name SET NAME= 'Mostly' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Mostly';
UPDATE concept_name SET NAME= 'Two' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Two';
UPDATE concept_name SET NAME= 'Greater than or 3' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Greater than or 3';
UPDATE concept_name SET NAME= 'HIVTC FU-Hospitalizations due to HIV in last 3 months' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Hospitalizations due to HIV in last 3 months';
UPDATE concept_name SET NAME= 'HIVTC FU-CD4 count performed in last 6 months' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, CD4 count performed in last 6 months and greater than 350';
UPDATE concept_name SET NAME= 'Unmarried' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Unmarried';
UPDATE concept_name SET NAME= 'Married' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Married';
UPDATE concept_name SET NAME= 'Divorced' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Divorced';
UPDATE concept_name SET NAME= 'Widowed' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Widowed';
UPDATE concept_name SET NAME= 'HIVTC FU-Marital status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Marital Status';
UPDATE concept_name SET NAME= 'HIVTC FU-CD4 count' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, CD4 count';
UPDATE concept_name SET NAME= 'HIVTC FU-CD4 count date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, CD4 Count Date';
UPDATE concept_name SET NAME= 'HIVTC FU-Viral load' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Viral Load';
UPDATE concept_name SET NAME= 'HIVTC FU-Viral load date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Viral Load date';
UPDATE concept_name SET NAME= 'HIVTC FU-IPT follow' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, IPT Follow-up';
UPDATE concept_name SET NAME= 'HIVTC FU-Transferred out to' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Transferred out to';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/LPV/r';
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/LPV/r';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC FU-Regimen when transferred out' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Regimen when transferred out';
UPDATE concept_name SET NAME= 'HIVTC FU-Date of transferred out' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Date of transferred out';
UPDATE concept_name SET NAME= 'HIVTC FU-Treatment switched date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Treatment switched date';
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/LPV/r';
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/LPV/r';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC FU-Name of switched regimem' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Name of Switched Regimem';
UPDATE concept_name SET NAME= 'Clinical treatment failure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Clinical treatment failure';
UPDATE concept_name SET NAME= 'Immunological failure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Immunological failure';
UPDATE concept_name SET NAME= 'Virologic failure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Virologic failure';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC FU-Reason for treatment switch' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Reason for treatment switch';
UPDATE concept_name SET NAME= 'HIVTC FU-Treatment substituted date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Treatment substituted date';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/LPV/r';
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/LPV/r';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC FU-New regimen' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, New Regimen';
UPDATE concept_name SET NAME= 'Toxic side effect' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Toxic Side Effect';
UPDATE concept_name SET NAME= 'Congestive Heart Failure-Examination follow up' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Congestive Heart Failure - Examination / Follow Up - Reason for Decompensation / Etiology - Reason for decompensation / Likely Etiology - Pregnancy';
UPDATE concept_name SET NAME= 'Risk of pregnancy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Risk of pregnancy';
UPDATE concept_name SET NAME= 'Newly diagnosed TB' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Newly diagnosed TB';
UPDATE concept_name SET NAME= 'New drug available' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='New drug available';
UPDATE concept_name SET NAME= 'Drug stockout' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Drug stockout';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'HIVTC FU-Reason for treatment substitution' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Reason for treatment substitution';
UPDATE concept_name SET NAME= 'HIVTC FU-Initial' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC-Initial';
UPDATE concept_name SET NAME= 'HIVTC FU-Followup' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC-Followup';
UPDATE concept_name SET NAME= 'HIVTC FU-Type of visit' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC-Type of Visit';
UPDATE concept_name SET NAME= 'OI-Bacterial pneumonia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Bacterial Pneumonia Opportunistic Infection';
UPDATE concept_name SET NAME= 'OI-Tuberculosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Tuberculosis Opportunistic Infection';
UPDATE concept_name SET NAME= 'OI-Candidiasis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Candidiasis Opportunistic Infection';
UPDATE concept_name SET NAME= 'Diarrhoea' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Diarrhoea';
UPDATE concept_name SET NAME= 'OI-Cryptococcus meningitis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Crypto Meningitis Opportunistic Infection';
UPDATE concept_name SET NAME= 'OI-Pneumocysitis pneumonia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pneumocysitis Pneumonia Opportunistic Infection';
UPDATE concept_name SET NAME= 'OI-Cytomegato virus' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cytomegato Virus Opportunistic Infection';
UPDATE concept_name SET NAME= 'OI-Herpes zoster' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Herpes Zoster Opportunistic Infection';
UPDATE concept_name SET NAME= 'OI-Herpes genitalis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Herpes Genitalis Opportunistic Infection';
UPDATE concept_name SET NAME= 'Toxo plasmosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Toxo Plasmosis';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'Not applicable' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Not applicable';
UPDATE concept_name SET NAME= 'HIVTC FU-Opportunistic infection diagnosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Opportunistic Infection Diagnosis';
UPDATE concept_name SET NAME= 'HIVTC FU-Other opportunistic infection diagnosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Other Opportunistic Infection Diagnosis';
UPDATE concept_name SET NAME= 'HIVTC FU-Any OI in past 3 months' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Any OI in past 3 months?';
UPDATE concept_name SET NAME= 'HIV-Provided cotrim' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIV-Provided Cotrim';
UPDATE concept_name SET NAME= 'HIVTC FU-Opportunistic infection treatment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Opportunistic Infection Treatment';
UPDATE concept_name SET NAME= 'HIVTC FU-TB screened' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, TB Screened';
UPDATE concept_name SET NAME= 'Started' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Started';
UPDATE concept_name SET NAME= 'Ongoing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Ongoing';
UPDATE concept_name SET NAME= 'Stopped' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stopped';
UPDATE concept_name SET NAME= 'HIVTC FU-CPT status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, CPT Status';
UPDATE concept_name SET NAME= 'HIVTC FU-HIV care cpt start date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, HIV care CPT start date';
UPDATE concept_name SET NAME= 'HIVTC FU-CPT stop date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, CPT Stop Date';
UPDATE concept_name SET NAME= 'On treatment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='On Treatment';
UPDATE concept_name SET NAME= 'Stopped treatment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stopped Treatment';
UPDATE concept_name SET NAME= 'Transferred out' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Transferred out';
UPDATE concept_name SET NAME= 'Missing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Missing';
UPDATE concept_name SET NAME= 'Lost to follow up' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Lost to Follow up';
UPDATE concept_name SET NAME= 'Colostomy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Colostomy';
UPDATE concept_name SET NAME= 'Restarted' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Restarted';
UPDATE concept_name SET NAME= 'HIVTC FU-ART current status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, ART current status';
UPDATE concept_name SET NAME= 'Adherence level A' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Adherence Level A';
UPDATE concept_name SET NAME= 'Adherence level B' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Adherence Level B';
UPDATE concept_name SET NAME= 'Adherence level C' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Adherence Level C';
UPDATE concept_name SET NAME= 'HIVTC FU-ART treatment adherence' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, ART Treatment Adherence';
UPDATE concept_name SET NAME= 'HIVTC FU-Need family planning assessment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Need Family Planning assessment';
UPDATE concept_name SET NAME= 'Oral contraceptives' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Oral Contraceptives';
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='IUCD';
UPDATE concept_name SET NAME= 'Permanent' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Permanent';
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Depo';
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Implant';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Condoms';
UPDATE concept_name SET NAME= 'HIVTC FU-FP methods used by the patient' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, FP methods used by the patient';
UPDATE concept_name SET NAME= 'HIVTC FU-Refer for FP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC-Progress Refer for FP';
UPDATE concept_name SET NAME= 'HIVTC FU-Weight' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Weight';
UPDATE concept_name SET NAME= 'Improved' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Improved';
UPDATE concept_name SET NAME= 'Same' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Same';
UPDATE concept_name SET NAME= 'Worse' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Worse';
UPDATE concept_name SET NAME= 'HIVTC FU-Follow up status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC-Follow Up Status';
UPDATE concept_name SET NAME= 'HIVTC FU-Followup' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Followup';
UPDATE concept_name SET NAME= 'HIVTC FU-Date of death' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Date of Death';
UPDATE concept_name SET NAME= 'HIVTC FU-Death cause' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Death cause';
UPDATE concept_name SET NAME= 'HIVTC FU-Transferred out' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Transferred out';
UPDATE concept_name SET NAME= 'HIVTC FU-Treatment switched' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Treatment Switched';
UPDATE concept_name SET NAME= 'HIVTC FU-Treatment substituted' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, Treatment Substituted';
UPDATE concept_name SET NAME= 'HIVTC FU-HIV treatment and care history' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, HIV Care and Treatment History';
UPDATE concept_name SET NAME= 'HIVTC FU-ART history' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIVTC, ART History';
UPDATE concept_name SET NAME= 'HIV Treatment and care (HIVTC) follow up note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HIV Treatment and Care Progress Template';


UPDATE concept_name SET NAME= 'Self' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Self' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other/Relatives' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Other or relatives' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Visit' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Visit' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Chief complaint' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Chief complaint' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Physical examination details' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Physical examination details' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'History of present illness' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-History of present illness' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Zero' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Zero' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Mostly' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Mostly' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Two' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Two' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Greater than or 3' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Greater than or 3' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Hospitalizations due to HIV in last 3 months' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Hospitalizations due to HIV in last 3 months' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CD4 count performed in last 6 months and greater than 350' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-CD4 count performed in last 6 months' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Unmarried' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Unmarried' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Married' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Married' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Divorced' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Divorced' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Widowed' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Widowed' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Marital status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Marital status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CD4 count' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-CD4 count' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CD4 count date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-CD4 count date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Viral load' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Viral load' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Viral load date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Viral load date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IPT follow' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-IPT follow' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Transferred out to' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Transferred out to' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Regimen when transferred out' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Regimen when transferred out' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Date of transferred out' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Date of transferred out' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Treatment switched date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Treatment switched date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Name of switched regimem' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Name of switched regimem' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Clinical treatment failure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Clinical treatment failure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Immunological failure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Immunological failure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Virologic failure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Virologic failure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Reason for treatment switch' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Reason for treatment switch' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Treatment substituted date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Treatment substituted date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'New regimen' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-New regimen' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Toxic side effect' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Toxic side effect' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Examination / follow up' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Congestive Heart Failure-Examination follow up' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Risk of pregnancy' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Risk of pregnancy' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Newly diagnosed TB' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Newly diagnosed TB' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'New drug available' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'New drug available' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Drug stockout' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Drug stockout' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Reason for treatment substitution' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Reason for treatment substitution' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Initial' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Initial' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Followup' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Followup' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Type of visit' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Type of visit' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Bacterial pneumonia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OI-Bacterial pneumonia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Tuberculosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OI-Tuberculosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Candidiasis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OI-Candidiasis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diarrhoea' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Diarrhoea' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cryptoccus meningitis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OI-Cryptococcus meningitis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pneumocysitis pneumonia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OI-Pneumocysitis pneumonia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cytomegato virus' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OI-Cytomegato virus' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Herpes zoster' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OI-Herpes zoster' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Herpes genitalis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OI-Herpes genitalis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Toxo plasmosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Toxo plasmosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Not applicable' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Not applicable' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Opportunistic infection diagnosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Opportunistic infection diagnosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other opportunistic infection diagnosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Other opportunistic infection diagnosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Any OI in past 3 months?' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Any OI in past 3 months' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Provided cotrim' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIV-Provided cotrim' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Opportunistic infection treatment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Opportunistic infection treatment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TB screened' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-TB screened' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Started' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Started' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Ongoing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Ongoing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stopped' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stopped' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CPT status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-CPT status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HIV care cpt start date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-HIV care cpt start date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CPT stop date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-CPT stop date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'On treatment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'On treatment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stopped treatment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stopped treatment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Transferred out' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Transferred out' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Missing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Missing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Lost to follow up' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Lost to follow up' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Colostomy' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Colostomy' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Restarted' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Restarted' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART current status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-ART current status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Adherence level A' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Adherence level A' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Adherence level B' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Adherence level B' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Adherence level C' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Adherence level C' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART treatment adherence' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-ART treatment adherence' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Need family planning assessment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Need family planning assessment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Oral contraceptives' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Oral contraceptives' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'IUCD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'IUCD' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Permanent' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Permanent' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Depo' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Depo' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Implant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Implant' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Condoms' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Condoms' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'FP methods used by the patient' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-FP methods used by the patient' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Refer for FP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Refer for FP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Weight' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Weight' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Improved' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Improved' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Same' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Same' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Worse' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Worse' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Follow up status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Follow up status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Followup' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Followup' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Date of death' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Date of death' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Death cause' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Death cause' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Transferred out' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Transferred out' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Treatment switched' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Treatment switched' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Treatment substituted' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-Treatment substituted' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HIV treatment and care history' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-HIV treatment and care history' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART history' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIVTC FU-ART history' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HIV Treatment and care follow up note' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HIV Treatment and care (HIVTC) follow up note' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );








