/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR DR TB INTAKE PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/


INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Intrapartum' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Postpartum' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Intrapartum' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Category B' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Category C' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Category D' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Category N' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Livebirth' ;
INSERT INTO concept_name (concept_id,name,locale,locale_preferred,creator,date_created,concept_name_type,voided,voided_by,date_voided,void_reason,uuid, date_changed,changed_by) SELECT concept_id,name,locale,locale_preferred, creator,date_created,'SHORT', voided,voided_by,date_voided,void_reason,UUID(),date_changed,changed_by FROM concept_name WHERE concept_name_type ='FULLY_SPECIFIED' and name = 'Exclusive Breast Feeding' ;


UPDATE concept_name SET NAME= 'Sex worker' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Sex worker';
UPDATE concept_name SET NAME= 'People who inject drugs' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='People who inject drugs';
UPDATE concept_name SET NAME= 'MSM and transgenders' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='MSM and transgenders';
UPDATE concept_name SET NAME= 'Blood or organ recipient' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Blood or organ recipient';
UPDATE concept_name SET NAME= 'Client of sex worker' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Client of sex worker';
UPDATE concept_name SET NAME= 'Migrant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Migrant';
UPDATE concept_name SET NAME= 'Spouse of migrant' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Spouse of migrant';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'PMTCT-Risk group' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Risk Group';
UPDATE concept_name SET NAME= 'PMTCT-Other risk group' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Other Risk Group';
UPDATE concept_name SET NAME= 'Before pregnancy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Before Pregnancy';
UPDATE concept_name SET NAME= 'Antenatal period' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Antenatal Period';
UPDATE concept_name SET NAME= 'Intrapartum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Intrapartum';
UPDATE concept_name SET NAME= 'Postpartum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Postpartum';
UPDATE concept_name SET NAME= 'PMTCT-Women identified HIV +ve during' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Women identified HIV Positive during';
UPDATE concept_name SET NAME= 'PMTCT-Diagnosed HIV +ve date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Diagnosed HIV +ve Date';
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Negative';
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Positive';
UPDATE concept_name SET NAME= 'PMTCT-Who already know their HIV status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Who already know their HIV status';
UPDATE concept_name SET NAME= 'PMTCT-Referred if the status is unknown' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Referred if the status is unknown';
UPDATE concept_name SET NAME= 'Stage I' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stage i';
UPDATE concept_name SET NAME= 'Stage II' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stage ii';
UPDATE concept_name SET NAME= 'Stage III' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stage iii';
UPDATE concept_name SET NAME= 'Stage IV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stage iv';
UPDATE concept_name SET NAME= 'PMTCT-WHO clinical staging' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, WHO clinical staging';
UPDATE concept_name SET NAME= 'PMTCT-CD4 count' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, CD4 count';
UPDATE concept_name SET NAME= 'PMTCT-ART planned start date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, ART Planned Start Date';
UPDATE concept_name SET NAME= 'Before pregnancy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Before Pregnancy';
UPDATE concept_name SET NAME= 'Antenatal period' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Antenatal Period';
UPDATE concept_name SET NAME= 'Intrapartum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Intrapartum';
UPDATE concept_name SET NAME= 'Postnatal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Postnatal';
UPDATE concept_name SET NAME= 'PMTCT-Started art during' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Started ART during';
UPDATE concept_name SET NAME= 'PMTCT-ART start date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, ART start date';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP';
UPDATE concept_name SET NAME= 'AZT/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV';
UPDATE concept_name SET NAME= 'AZT/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP';
UPDATE concept_name SET NAME= 'TDF/3TC/NVP-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/NVP-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV';
UPDATE concept_name SET NAME= 'TDF/3TC/EFV-Paediatric' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/EFV-Paediatric';
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='TDF/3TC/LPV/r';
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='AZT/3TC/LPV/r';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'PMTCT-ART regimen' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, ART Regimen';
UPDATE concept_name SET NAME= 'PMTCT-CD4 count after 6 months' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, CD4 count after 6 months';
UPDATE concept_name SET NAME= 'PMTCT-CD4 count after 12 months' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, CD4 count after 12 months';
UPDATE concept_name SET NAME= 'Category A' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Category A';
UPDATE concept_name SET NAME= 'Category B' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Category B';
UPDATE concept_name SET NAME= 'Category C' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Category C';
UPDATE concept_name SET NAME= 'Category D' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Category D';
UPDATE concept_name SET NAME= 'Category X' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Category X';
UPDATE concept_name SET NAME= 'Category N' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Category N';
UPDATE concept_name SET NAME= 'PMTCT-Pregnancy category when TB treatment started' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Pregnancy category when TB treatment started';
UPDATE concept_name SET NAME= 'PMTCT-TB treatment start date' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, TB treatment start date';
UPDATE concept_name SET NAME= 'On treatment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='On treatment';
UPDATE concept_name SET NAME= 'Stopped treatment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stopped treatment';
UPDATE concept_name SET NAME= 'Transferred out' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Transferred out';
UPDATE concept_name SET NAME= 'Missing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Missing';
UPDATE concept_name SET NAME= 'Lost to follow up' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Lost to follow up';
UPDATE concept_name SET NAME= 'Death' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Death';
UPDATE concept_name SET NAME= 'PMTCT-Antepartum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Antepartum';
UPDATE concept_name SET NAME= 'Adherence level A' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Adherence level a';
UPDATE concept_name SET NAME= 'Adherence level B' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Adherence level b';
UPDATE concept_name SET NAME= 'Adherence level C' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Adherence level c';
UPDATE concept_name SET NAME= 'PMTCT-Adherence level' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Adherence Level';
UPDATE concept_name SET NAME= 'Normal delivery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Normal Delivery';
UPDATE concept_name SET NAME= 'Vaccum delivery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Vaccum Delivery';
UPDATE concept_name SET NAME= 'Forceps delivery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Forceps Delivery';
UPDATE concept_name SET NAME= 'Cesarean section delivery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cesarean Section Delivery';
UPDATE concept_name SET NAME= 'PMTCT-Delivery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Delivery';
UPDATE concept_name SET NAME= 'Livebirth' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Livebirth';
UPDATE concept_name SET NAME= 'Stillbirth' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stillbirth';
UPDATE concept_name SET NAME= 'Stillbirth macerated' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stillbirth Macerated';
UPDATE concept_name SET NAME= 'PMTCT-Baby birth status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Baby birth status';
UPDATE concept_name SET NAME= 'On treatment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='On treatment';
UPDATE concept_name SET NAME= 'Stopped treatment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Stopped treatment';
UPDATE concept_name SET NAME= 'Transferred out' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Transferred out';
UPDATE concept_name SET NAME= 'Missing' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Missing';
UPDATE concept_name SET NAME= 'Lost to follow up' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Lost to follow up';
UPDATE concept_name SET NAME= 'Death' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Death';
UPDATE concept_name SET NAME= 'PMTCT-Postpartum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Postpartum';
UPDATE concept_name SET NAME= 'PMTCT-Live birth' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Live Birth';
UPDATE concept_name SET NAME= 'PMTCT-Birth weight' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Birth Weight';
UPDATE concept_name SET NAME= 'PMTCT-Started ARV prophylaxis for baby' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Started ARV Prophylaxis for Baby';
UPDATE concept_name SET NAME= 'Exclusive breast feeding' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Exclusive Breast Feeding';
UPDATE concept_name SET NAME= 'Replacement breast feeding' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Replacement Breast Feeding';
UPDATE concept_name SET NAME= 'Mixed breast feeding' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Mixed Breast Feeding';
UPDATE concept_name SET NAME= 'PMTCT-Breast feeding options opted by HIV +ve mother' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Breast feeding options opted by HIV +ve mother';
UPDATE concept_name SET NAME= 'PMTCT-Family planning services provided postpartum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Family Planning services provided postpartum';
UPDATE concept_name SET NAME= 'PMTCT-Transfer out during pregnancy' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Transfer out during pregnancy';
UPDATE concept_name SET NAME= 'PMTCT-Date of death' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Date of Death';
UPDATE concept_name SET NAME= 'PMTCT-Place of transfer out for continum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Place of transfer out for continuum';
UPDATE concept_name SET NAME= 'PMTCT-Date of transfer out for continum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Date of Transfer out for continuum';
UPDATE concept_name SET NAME= 'PMTCT-Remarks of transfer out for continum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Remarks of transfer out for continuum';
UPDATE concept_name SET NAME= 'PMTCT-Women identified HIV +ve' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Women identified HIV Positive';
UPDATE concept_name SET NAME= 'PMTCT-HIV status of male partner' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, HIV Status of Male Partner';
UPDATE concept_name SET NAME= 'PMTCT-ART eligibility and date for first' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, ART Eligibility and Date for First';
UPDATE concept_name SET NAME= 'PMTCT-ART treatment' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, ART Treatment';
UPDATE concept_name SET NAME= 'PMTCT-CD4 count after' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, CD4 count after';
UPDATE concept_name SET NAME= 'PMTCT-TB treatment during' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, TB Treatment During';
UPDATE concept_name SET NAME= 'PMTCT-Follow up on ART' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Follow-up on ART';
UPDATE concept_name SET NAME= 'PMTCT-HIV +ve born babies' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, HIV Positive Born Babies';
UPDATE concept_name SET NAME= 'PMTCT-Date and place of transfer out for continum' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, Date and Place of Transfer out for continuum';
UPDATE concept_name SET NAME= 'PMTCT-End of follow up' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='PMTCT, End of Follow-up';
UPDATE concept_name SET NAME= 'Prevention of Mother to child  transmission(PMTCT) note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Prevention of Mother-to-Child Transmission Intake Template';

UPDATE concept_name SET NAME= 'Sex worker' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Sex worker' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'People who inject drugs' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'People who inject drugs' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'MSM and transgenders' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'MSM and transgenders' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Blood or organ recipient' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Blood or organ recipient' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Client of sex worker' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Client of sex worker' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Migrant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Migrant' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Spouse of migrant' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Spouse of migrant' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Risk group' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Risk group' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other risk group' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Other risk group' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Before pregnancy' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Before pregnancy' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Antenatal period' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Antenatal period' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Intrapartum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Intrapartum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Postpartum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Postpartum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Women identified hiv positive during' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Women identified HIV +ve during' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diagnosed HIV +ve date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Diagnosed HIV +ve date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Negative' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Negative' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Positive' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Positive' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Who already know their HIV status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Who already know their HIV status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Referred if the status is unknown' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Referred if the status is unknown' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stage I' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stage I' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stage II' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stage II' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stage III' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stage III' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stage IV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stage IV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'WHO clinical staging' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-WHO clinical staging' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CD4 count' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-CD4 count' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART planned start date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-ART planned start date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Before pregnancy' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Before pregnancy' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Antenatal period' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Antenatal period' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Intrapartum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Intrapartum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Postnatal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Postnatal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Started art during' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Started art during' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART start date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-ART start date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/NVP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/NVP-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/EFV' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Paediatric' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/EFV-Paediatric' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TDF/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'TDF/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'AZT/3TC/LPV/r' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'AZT/3TC/LPV/r' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART regimen' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-ART regimen' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CD4 count after 6 months' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-CD4 count after 6 months' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CD4 count after 12 months' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-CD4 count after 12 months' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category A' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Category A' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category B' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Category B' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category C' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Category C' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category D' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Category D' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category X' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Category X' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Category N' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Category N' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pregnancy category when TB treatment started' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Pregnancy category when TB treatment started' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TB treatment start date' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-TB treatment start date' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'On treatment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'On treatment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stopped treatment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stopped treatment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Transferred out' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Transferred out' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Missing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Missing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Lost to follow up' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Lost to follow up' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Death' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Death' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Antepartum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Antepartum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Adherence level A' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Adherence level A' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Adherence level B' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Adherence level B' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Adherence level C' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Adherence level C' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Adherence level' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Adherence level' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Normal delivery' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Normal delivery' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Vaccum delivery' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Vaccum delivery' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Forceps delivery' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Forceps delivery' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cesarean section delivery' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Cesarean section delivery' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Delivery' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Delivery' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Livebirth' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Livebirth' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stillbirth' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stillbirth' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stillbirth macerated' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stillbirth macerated' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Baby birth status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Baby birth status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'On treatment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'On treatment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Stopped treatment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Stopped treatment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Transferred out' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Transferred out' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Missing' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Missing' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Lost to follow up' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Lost to follow up' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Death' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Death' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Postpartum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Postpartum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Live birth' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Live birth' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Birth weight' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Birth weight' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Started ARV prophylaxis for baby' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Started ARV prophylaxis for baby' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Exclusive breast feeding' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Exclusive breast feeding' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Replacement breast feeding' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Replacement breast feeding' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Mixed breast feeding' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Mixed breast feeding' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Breast feeding options opted by HIV +ve mother' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Breast feeding options opted by HIV +ve mother' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Family planning services provided postpartum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Family planning services provided postpartum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Transfer out during pregnancy' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Transfer out during pregnancy' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Date of death' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Date of death' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Place of transfer out for continum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Place of transfer out for continum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Date of transfer out for continum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Date of transfer out for continum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Remarks of transfer out for continum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Remarks of transfer out for continum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Women identified HIV +ve' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Women identified HIV +ve' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HIV status of male partner' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-HIV status of male partner' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART eligibility and date for first' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-ART eligibility and date for first' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ART treatment' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-ART treatment' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'CD4 count after' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-CD4 count after' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'TB treatment during' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-TB treatment during' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Follow up on ART' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Follow up on ART' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'HIV +ve born babies' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-HIV +ve born babies' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Date and place of transfer out for continum' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-Date and place of transfer out for continum' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'End of follow up' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'PMTCT-End of follow up' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'PMTCT note' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Prevention of Mother to child  transmission(PMTCT) note' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );