/*
OBJECTIVE : TO UPDATE THE CONCEPT NAMES FOR DR TB INTAKE PROGRAM TEMPLATE TO MAKE THEM STANDARD NAMES
CREATED BY:  DIWASH
REVIEWED BY: DIPAK,SURUCHI,LAXMAN
DATE : 20TH NOVEMBER, 2018
*/
UPDATE concept_name SET NAME= 'Anesthesia-Date of procedure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Date of procedure';
UPDATE concept_name SET NAME= 'Anesthesia-Pre operation diagnosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Pre operation diagnosis';
UPDATE concept_name SET NAME= 'Anesthesia-Proposed operation' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Proposed operation';
UPDATE concept_name SET NAME= 'Anesthesia-Person assisting anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Person assisting anesthesia';
UPDATE concept_name SET NAME= 'Anesthesia-Surgeon' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Surgeon';
UPDATE concept_name SET NAME= 'Anesthesia-Expected duration of surgery' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Expected duration of Surgery';
UPDATE concept_name SET NAME= 'Anesthesia-Expected blood loss' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Expected blood loss';
UPDATE concept_name SET NAME= 'Anesthesia-Coexisting disease' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Co-existing disease/medication';
UPDATE concept_name SET NAME= 'Anesthesia-Allergic history' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Allergic history';
UPDATE concept_name SET NAME= 'Anesthesia-History of tobacco alcohol' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-History of Tobacco/Alcohol';
UPDATE concept_name SET NAME= 'Anesthesia-Previous anesthesia exposure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Previous anesthesia exposure';
UPDATE concept_name SET NAME= 'Chest pain' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Chest pain';
UPDATE concept_name SET NAME= 'Palliation' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Palliation';
UPDATE concept_name SET NAME= 'Sweating' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Sweating';
UPDATE concept_name SET NAME= 'Dyspnea' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Dyspnea';
UPDATE concept_name SET NAME= 'Swelling' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Swelling';
UPDATE concept_name SET NAME= 'HTN-COPD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HTN, COPD';
UPDATE concept_name SET NAME= 'Anesthesia-Cardiovascular problem' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Cardiovascular problem';
UPDATE concept_name SET NAME= 'SOB' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='SOB';
UPDATE concept_name SET NAME= 'Asthama' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Asthama';
UPDATE concept_name SET NAME= 'COPD' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='COPD';
UPDATE concept_name SET NAME= 'Pulmonary tuberculosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pulmonary Tuberculosis';
UPDATE concept_name SET NAME= 'Acute nasopharyngitis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Acute nasopharyngitis (Common cold)';
UPDATE concept_name SET NAME= 'Anesthesia-Respiratory problem' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Respiratory problem';
UPDATE concept_name SET NAME= 'Thyroid problem' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Thyroid problem';
UPDATE concept_name SET NAME= 'Diabetes mellitus' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Diabetes Mellitus';
UPDATE concept_name SET NAME= 'Anesthesia-Endocrine problem' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Endocrine problem';
UPDATE concept_name SET NAME= 'Bowel bladder' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Bowel/bladder';
UPDATE concept_name SET NAME= 'Contraceptives' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Contraceptives';
UPDATE concept_name SET NAME= 'Anesthesia-Genitourinary problem' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Genitourinary problem';
UPDATE concept_name SET NAME= 'ER-Date of LMP' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ER General Notes, Date of LMP';
UPDATE concept_name SET NAME= 'Convulsion' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Convulsion';
UPDATE concept_name SET NAME= 'Arthritis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Arthritis';
UPDATE concept_name SET NAME= 'Mental disorder' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Mental disorder';
UPDATE concept_name SET NAME= 'Anesthesia-Nervous and musculoskeletal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Nervous and musculoskeletal';
UPDATE concept_name SET NAME= 'Anesthesia-Bleeding disorder' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Bleeding disorder';
UPDATE concept_name SET NAME= 'Family history' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Family History';
UPDATE concept_name SET NAME= 'BP data-Systolic' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='BP data-Systolic';
UPDATE concept_name SET NAME= 'BP Systolic Data-Systolic abnormal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='BP Systolic Data-Systolic Abnormal';
UPDATE concept_name SET NAME= 'BP Diastolic Data-Diastolic' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='BP Diastolic Data-Diastolic';
UPDATE concept_name SET NAME= 'BP Diastolic Data-Diastolic abnormal' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='BP Diastolic Data-Diastolic Abnormal';
UPDATE concept_name SET NAME= 'Sitting' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Sitting';
UPDATE concept_name SET NAME= 'Supine' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Supine';
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Others';
UPDATE concept_name SET NAME= 'Posture' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Posture';
UPDATE concept_name SET NAME= 'Temperature' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Temperature';
UPDATE concept_name SET NAME= 'Heart rate' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Heart rate';
UPDATE concept_name SET NAME= 'Respiratory rate' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Respiratory rate';
UPDATE concept_name SET NAME= 'Weight' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Weight';
UPDATE concept_name SET NAME= 'Jaundice' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Jaundice';
UPDATE concept_name SET NAME= 'Anemia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anemia';
UPDATE concept_name SET NAME= 'Cynosis' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Cynosis';
UPDATE concept_name SET NAME= 'Edema' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Edema';
UPDATE concept_name SET NAME= 'Dehydration' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Dehydration';
UPDATE concept_name SET NAME= 'Anesthesia-General examination' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-General examination';
UPDATE concept_name SET NAME= '< 3 fingers' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='< 3 fingers';
UPDATE concept_name SET NAME= '> 3 fingers' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='> 3 fingers';
UPDATE concept_name SET NAME= 'Anesthesia-Mouth opening' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Mouth opening';
UPDATE concept_name SET NAME= 'Anesthesia-Teeth examination' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Teeth examination';
UPDATE concept_name SET NAME= 'Free' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Free';
UPDATE concept_name SET NAME= 'Restricted' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Restricted';
UPDATE concept_name SET NAME= 'Anesthesia-Temporomandibular joint (TMJ)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Temporomandibular joint (TMJ)';
UPDATE concept_name SET NAME= '< 3 fingers' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='< 3 fingers';
UPDATE concept_name SET NAME= '> 3 fingers' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='> 3 fingers';
UPDATE concept_name SET NAME= 'Anesthesia-Thyromental distance' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Thyromental distance';
UPDATE concept_name SET NAME= 'Free' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Free';
UPDATE concept_name SET NAME= 'Restricted' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Restricted';
UPDATE concept_name SET NAME= 'Anesthesia-Neck movement' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Neck movement';
UPDATE concept_name SET NAME= 'One' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='One';
UPDATE concept_name SET NAME= 'Two' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Two';
UPDATE concept_name SET NAME= 'Three' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='three';
UPDATE concept_name SET NAME= 'Four' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='four';
UPDATE concept_name SET NAME= 'Anesthesia-Malampatti grading' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Malampatti grading';
UPDATE concept_name SET NAME= 'Anesthesia-Systemic examination' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Systemic examination';
UPDATE concept_name SET NAME= 'OPD-ROS notes' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='OPD-ROS notes';
UPDATE concept_name SET NAME= 'Lab' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Lab';
UPDATE concept_name SET NAME= 'X ray' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='X Ray';
UPDATE concept_name SET NAME= 'ECG remarks' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='ECG Remarks';
UPDATE concept_name SET NAME= 'One' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='One';
UPDATE concept_name SET NAME= 'Two' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Two';
UPDATE concept_name SET NAME= 'Three' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='three';
UPDATE concept_name SET NAME= 'Four' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='four';
UPDATE concept_name SET NAME= 'five' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='five';
UPDATE concept_name SET NAME= 'Operative Note-Emergency' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Operative Note-Emergency';
UPDATE concept_name SET NAME= 'Anesthesia-ASA status' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-ASA status';
UPDATE concept_name SET NAME= 'Yes' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Yes';
UPDATE concept_name SET NAME= 'No' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='No';
UPDATE concept_name SET NAME= 'Review later' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Review later';
UPDATE concept_name SET NAME= 'Anesthesia-Fitness for anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Fitness for anesthesia';
UPDATE concept_name SET NAME= 'General anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='General Anesthesia';
UPDATE concept_name SET NAME= 'Intravenous anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Intravenous anesthesia';
UPDATE concept_name SET NAME= 'Procedure note-Regional anesthesia' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Procedure note-Regional anesthesia';
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Other';
UPDATE concept_name SET NAME= 'Anesthesia-Anesthesia plan' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Anesthesia plan';
UPDATE concept_name SET NAME= 'Anesthesia-Other (specify)' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Other (specify)';
UPDATE concept_name SET NAME= 'Anesthesia-IV canulation' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia_IV Canulation';
UPDATE concept_name SET NAME= 'Anesthesia-Blood arrangement' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia_Blood arrangement';
UPDATE concept_name SET NAME= 'HTC-Informed consent' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='HCT, Informed Consent';
UPDATE concept_name SET NAME= 'Anesthesia-Pre operaive insruction' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Pre-operative instruction';
UPDATE concept_name SET NAME= 'Anesthesia-Medical history' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Medical history';
UPDATE concept_name SET NAME= 'Systolic data' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Systolic Data';
UPDATE concept_name SET NAME= 'Diastolic' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Diastolic';
UPDATE concept_name SET NAME= 'Blood pressure' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Blood pressure';
UPDATE concept_name SET NAME= 'Anesthesia-Airway evaluation' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Airway evaluation';
UPDATE concept_name SET NAME= 'Anesthesia-Physical examination' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Physical examination';
UPDATE concept_name SET NAME= 'Anesthesia-Investigation review' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Anesthesia-Investigation review';
UPDATE concept_name SET NAME= 'Pre anesthesia check up note' WHERE concept_name_type='FULLY_SPECIFIED' AND NAME='Pre Anesthesia Check up';

UPDATE concept_name SET NAME= 'Date of procedure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Date of procedure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pre operation diagnosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Pre operation diagnosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Proposed operation' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Proposed operation' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Person assisting anesthesia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Person assisting anesthesia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Surgeon' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Surgeon' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Expected duration of surgery' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Expected duration of surgery' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Expected blood loss' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Expected blood loss' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Co-existing disease/medication' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Coexisting disease' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Allergic history' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Allergic history' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'History of tobacco/alcohol' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-History of tobacco alcohol' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Previous anesthesia exposure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Previous anesthesia exposure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Chest pain' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Chest pain' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Palliation' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Palliation' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Sweating' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Sweating' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Dyspnea' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Dyspnea' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Swelling' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Swelling' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'COPD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HTN-COPD' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cardiovascular problem' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Cardiovascular problem' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'SOB' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'SOB' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Asthama' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Asthama' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'COPD' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'COPD' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pulmonary tuberculosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pulmonary tuberculosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Acute nasopharyngitis (common cold)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Acute nasopharyngitis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Respiratory problem' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Respiratory problem' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Thyroid problem' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Thyroid problem' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diabetes mellitus' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Diabetes mellitus' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Endocrine problem' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Endocrine problem' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Bowel/bladder' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Bowel bladder' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Contraceptives' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Contraceptives' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Genitourinary problem' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Genitourinary problem' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Date of LMP' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ER-Date of LMP' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Convulsion' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Convulsion' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Arthritis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Arthritis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Mental disorder' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Mental disorder' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Nervous and musculoskeletal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Nervous and musculoskeletal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Bleeding disorder' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Bleeding disorder' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Family history' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Family history' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Systolic' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'BP data-Systolic' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Systolic abnormal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'BP Systolic Data-Systolic abnormal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diastolic' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'BP Diastolic Data-Diastolic' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diastolic abnormal' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'BP Diastolic Data-Diastolic abnormal' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Sitting' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Sitting' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Supine' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Supine' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Others' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Others' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Posture' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Posture' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Temperature' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Temperature' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Heart rate' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Heart rate' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Respiratory rate' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Respiratory rate' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Weight' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Weight' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Jaundice' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Jaundice' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Anemia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anemia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Cynosis' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Cynosis' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Edema' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Edema' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Dehydration' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Dehydration' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'General examination' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-General examination' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '< 3 fingers' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '< 3 fingers' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '> 3 fingers' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '> 3 fingers' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Mouth opening' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Mouth opening' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Teeth examination' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Teeth examination' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Free' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Free' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Restricted' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Restricted' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Temporomandibular joint (TMJ)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Temporomandibular joint (TMJ)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '< 3 fingers' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '< 3 fingers' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= '> 3 fingers' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = '> 3 fingers' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Thyromental distance' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Thyromental distance' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Free' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Free' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Restricted' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Restricted' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Neck movement' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Neck movement' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'One' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'One' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Two' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Two' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Three' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Three' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Four' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Four' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Malampatti grading' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Malampatti grading' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Systemic examination' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Systemic examination' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ROS notes' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'OPD-ROS notes' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Lab' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Lab' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'X ray' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'X ray' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ECG remarks' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'ECG remarks' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'One' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'One' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Two' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Two' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Three' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Three' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Four' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Four' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'five' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'five' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Emergency' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Operative Note-Emergency' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'ASA status' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-ASA status' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Yes' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Yes' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'No' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'No' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Review later' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Review later' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Fitness for anesthesia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Fitness for anesthesia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'General anesthesia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'General anesthesia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Intravenous anesthesia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Intravenous anesthesia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Regional anesthesia' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Procedure note-Regional anesthesia' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Other' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Anesthesia plan' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Anesthesia plan' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Other (specify)' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Other (specify)' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Anesthesia_IV canulation' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-IV canulation' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Anesthesia_Blood arrangement' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Blood arrangement' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Informed consent' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'HTC-Informed consent' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pre operative insruction' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Pre operaive insruction' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Medical history' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Medical history' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Sytolic data' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Systolic data' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Diastolic' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Diastolic' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Blood pressure' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Blood pressure' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Airway evaluation' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Airway evaluation' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Physical examination' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Physical examination' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Investigation review' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Anesthesia-Investigation review' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );
UPDATE concept_name SET NAME= 'Pre anesthesia check up note' WHERE concept_name_type='SHORT' AND CONCEPT_ID=(SELECT a.CONCEPT_ID FROM (select * from concept_name WHERE NAME = 'Pre anesthesia check up note' AND concept_name_type='FULLY_SPECIFIED' limit 1) a );